---
title: "Reaction Times - DG"
author: "Brooke Staveland"
date: "12/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 12,  # set default width of figures
  fig.height = 6,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(lme4)

## hand written functions ##

source('~/Projects/nice_r_functions/ggpaired_pretty.R')

```

# Intro

These scripts are to examines the reaction times across subjects in order to determine on a binning process time-locked either to choice time or presentation time (or both). We will run our regressions in each bin so this step is critical to get right. We want to make sure that we are binning such that we can capture meaingful snapshots of neural behavior, but we do not want to standardize/extend the time bins in a way that is inconsistent across people. In other words, we do not want to split the time between presentation and choice into thirds, if that means participant A will have 600ms bins and participant B will 100ms bins. It is also perferable that all subjects have close to the same number of bins. Finally, we want the bins to be small enough that we are not averaging over interesting neural beahvior.

