---
title: "Anatomy Plot Prep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 12,  # set default width of figures
  fig.height <- 6,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(beepr)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
# ggthemr("solarized")

# ## paralellization ##
# nCores <- 2
# registerDoParallel(nCores)

```

```{r load-elec-data}

# read in elec data #
elecs_9 <- read_csv(path(here(), "munge", "savio_cluster", "IR9_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_10 <- read_csv(path(here(), "munge", "savio_cluster", "IR10_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_16 <- read_csv(path(here(), "munge", "savio_cluster", "IR16_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_26 <- read_csv(path(here(), "munge", "savio_cluster", "IR26_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_28 <- read_csv(path(here(), "munge", "savio_cluster", "IR28_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_35 <- read_csv(path(here(), "munge", "savio_cluster", "IR35_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_57 <- read_csv(path(here(), "munge", "savio_cluster", "IR57_electrodes_presentation_locked_rscaler_2575.csv"))
elecs_cp34 <- read_csv(path(here(), "munge", "savio_cluster", "CP34-1_electrodes_presentation_locked_rscaler_2575.csv"))


# function to clean elec names #
clean_elecs <- function(df, sub){
  df <- df %>%
    rename(electrode = Var1) %>%
    select(electrode) %>%
    mutate(electrode = gsub("POL ", "", electrode)) %>%
    mutate(electrode = gsub(" POL", "", electrode)) %>%
    mutate(electrode = gsub("-Ref", "", electrode)) %>%
    mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
    mutate(sub = sub)
}

# clean elecs #
cleaned_elecs_9 <- clean_elecs(elecs_9, "IR9")
cleaned_elecs_10 <- clean_elecs(elecs_10, "IR10")
cleaned_elecs_16 <- clean_elecs(elecs_16, "IR16")
cleaned_elecs_26 <- clean_elecs(elecs_26, "IR26")
cleaned_elecs_28 <- clean_elecs(elecs_28, "IR28")
cleaned_elecs_35 <- clean_elecs(elecs_35, "IR35")
cleaned_elecs_57 <- clean_elecs(elecs_57, "IR57")
cleaned_elecs_cp34 <- clean_elecs(elecs_cp34, "CP34")
```



```{r localization-data}
merge_with_elec_info <- function(df, localizations_sub) {
## merge df with elec info, stored in localizations_sub
## creates new var of form ROI1-ROI2  
## also cleans elec names
  
  # clean the names
  df <- df %>%
    mutate(electrode = gsub("POL ", "", electrode)) %>%
    mutate(electrode = gsub(" POL", "", electrode)) %>%
    mutate(electrode = gsub("-Ref", "", electrode)) %>%
    mutate(electrode = gsub("-Ref-", "-", electrode)) 
  
  # separate two electrodes
  df <- df %>%
    mutate(first_elec= gsub("-.*", "", electrode)) %>%
    mutate(second_elec = gsub(".*-", "", electrode))
  # join on first electrode
  df <- left_join(df,
                 localizations_sub,
                 by = c("first_elec" = "Electrode"))
  # rename to `first_region`
  df <- df %>%
    rename(first_region = `Loc Meeting`)
  # join on second electrode and rename
  df <-  left_join(df,
             localizations_sub,
             by = c("second_elec" = "Electrode")) %>%
    rename(second_region = `Loc Meeting`) 
  # paste into useful format
  df <- df %>% mutate(ROI = paste0(first_region, "-", second_region))
  
  return(df)

}


## separate localtion data ##
localizations <- read_csv(path(here(), "munge", "combined_electrode_info_with_bob.csv"))
localizations_28 <- localizations %>% filter(subject == "IR28") %>% select(Electrode, `Loc Meeting`)
localizations_35 <- localizations %>% filter(subject == "IR35") %>% select(Electrode, `Loc Meeting`)
localizations_26 <- localizations %>% filter(subject == "IR26") %>% select(Electrode, `Loc Meeting`)
localizations_9 <- localizations %>% filter(subject == "IR9") %>% select(Electrode, `Loc Meeting`)
localizations_10 <- localizations %>% filter(subject == "IR10") %>% select(Electrode, `Loc Meeting`)
localizations_10 <- localizations_10 %>%
  mutate(Electrode = gsub("POL ", "", Electrode)) %>%
  mutate(Electrode = gsub(" POL", "", Electrode)) %>%
  mutate(Electrode = gsub("-Ref", "", Electrode)) %>%
  mutate(Electrode = gsub("-Ref-", "-", Electrode)) 
localizations_26 <- localizations %>% filter(subject == "IR26") %>% select(Electrode, `Loc Meeting`)
localizations_16 <- localizations %>% filter(subject == "IR16") %>% select(Electrode, `Loc Meeting`)
localizations_57 <- localizations %>% filter(subject == "IR57") %>% select(Electrode, `Loc Meeting`)
localizations_cp34 <- localizations %>% filter(subject == "CP34") %>% select(Electrode, `Loc Meeting`)


## merge with bipolar names ##
named_elecs_9 <- merge_with_elec_info(cleaned_elecs_9, localizations_9)
named_elecs_10 <- merge_with_elec_info(cleaned_elecs_10, localizations_10)
named_elecs_16 <- merge_with_elec_info(cleaned_elecs_16, localizations_16)
named_elecs_26 <- merge_with_elec_info(cleaned_elecs_26, localizations_26)
named_elecs_28 <- merge_with_elec_info(cleaned_elecs_28, localizations_28)
named_elecs_35 <- merge_with_elec_info(cleaned_elecs_35, localizations_35)
named_elecs_57 <- merge_with_elec_info(cleaned_elecs_57, localizations_57)
named_elecs_cp34 <- merge_with_elec_info(cleaned_elecs_cp34, localizations_cp34)


## merge together ##
named_elecs <- rbind(named_elecs_9,
                     named_elecs_10,
                     named_elecs_16,
                     named_elecs_26,
                     named_elecs_28,
                     named_elecs_35,
                     named_elecs_57,
                     named_elecs_cp34)

```


```{r roi-only-values}

create_roi_elec_files <- function(named_elecs, grep_search_1, grep_search_2, file_roi_name) {
  
    # create df for plotting #
    roi_df <- named_elecs %>%
      mutate(current_roi = if_else(grepl(grep_search_1, ROI, ignore.case = T), 1,
                               if_else(grepl(grep_search_2, ROI, ignore.case = T), 1, 0))) %>%
      select(sub, electrode, current_roi)  %>%
      filter(sub %in% c("IR9", "IR10", "IR16", "IR26", "IR28", "IR35", "IR57", "CP34")) %>%
      mutate(values = if_else(current_roi == 1 & sub == "IR9", 1, 
                              if_else(current_roi == 1 & sub == "IR10", 2, 
                                      if_else(current_roi == 1 & sub == "IR16", 3,
                                             if_else(current_roi == 1 & sub == "IR26", 4,
                                                  if_else(current_roi == 1 & sub == "IR28", 5,
                                                      if_else(current_roi == 1 & sub == "IR35", 6,
                                                              if_else(current_roi == 1 & sub == "IR57", 7, 
                                                                      if_else(current_roi == 1 & sub == "CP34", 8, 0))))))))) 
    # only current_roi electrodes #
    roi_electrodes <- roi_df %>% 
      filter(current_roi == 1) %>%
      select(electrode, sub)
    
    # all elecs but with values coding cing #
    roi_values <- roi_df %>% select(sub, electrode, values)
      
    ## write csvs ##
    # write elec specific #
    write_csv(roi_electrodes, path(here(), "figures", "anat_values", paste0(file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR9"), path(here(), "figures", "anat_values", paste0("IR9_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR10"), path(here(), "figures", "anat_values", paste0("IR10_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR16"), path(here(), "figures", "anat_values", paste0("IR16_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR26"), path(here(), "figures", "anat_values", paste0("IR26_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR28"), path(here(), "figures", "anat_values", paste0("IR28_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR35"), path(here(), "figures", "anat_values", paste0("IR35_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "IR57"), path(here(), "figures", "anat_values", paste0("IR57_", file_roi_name, "_electrodes.csv")))
    write_csv(roi_electrodes %>% filter(sub == "CP34"), path(here(), "figures", "anat_values", paste0("CP34_", file_roi_name, "_electrodes.csv")))
    # write calues #
    write_csv(roi_values, path(here(), "figures", "anat_values", paste0(file_roi_name, "_values.csv")))

}

create_roi_elec_files(named_elecs, "cing", "CC", "cingulate")
create_roi_elec_files(named_elecs, "[i|s|m]tg", "temporal gyrus", "temporal")
create_roi_elec_files(named_elecs, "ofc", "orbit", "ofc")
create_roi_elec_files(named_elecs, "sts", "superior temporal", "sts")
create_roi_elec_files(named_elecs, "mfg", "medial frontal", "mfg")

```


```{r sig-regressions-function}

# load_regression results #
regression_results <- read_csv(path(here(), "results", "compiled_regressions", "all_results_12-21-20.csv"))

# function to write all csvs necessary for matlab viz #
write_sig_roi_csvs <- function(regression_results, file_roi_name, freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), PVAL = .05){
    

    # load roi values #
    roi_values <- read_csv(path(here(), "figures", "anat_values", paste0(file_roi_name, "_values.csv")))
    
    # merge with values #
    roi_regressions <- merge.data.frame(regression_results, roi_values, by = c("sub", "electrode"))
    
    # loop over frequencies #
    for(band in freq_bands) {
    
      # get laterality #
      roi_band_regressions <- roi_regressions %>%
        mutate(lat = if_else(grepl("^L", electrode), "L",
                             if_else(grepl("^R", electrode), "R", "um"))) %>%
        # IR28 seems to have switched laterality...
        mutate(lat = if_else(sub == "IR28" & lat == "L", "R",
                             if_else(sub == "IR28" & lat == "R", "L", lat))) %>%
        # set frequency
      filter(freq == band)
        
      
      ### filter to significant cingulate ###
      # any cingulate across all conditions-- all elecs are sig #
      sig_cing_elecs <- roi_band_regressions %>%
        filter(values > 0) %>%
        select(sub, electrode, values, perm_p, epoch, predictor) %>%
        distinct() %>%
        mutate(sig = if_else(perm_p < PVAL, 1, 0)) %>%
        group_by(sub, electrode) %>%
        mutate(cing_pvals = if_else(sum(sig) > 0 & sub == "IR9", 1, 
                                if_else(sum(sig) > 0L & sub == "IR10", 2, 
                                        if_else(sum(sig) > 0 & sub == "IR16", 3,
                                                if_else(sum(sig) > 0 & sub == "IR26", 4,
                                                    if_else(sum(sig) > 0 & sub == "IR28", 5,
                                                        if_else(sum(sig) > 0 & sub == "IR35", 6,
                                                                if_else(sum(sig) > 0 & sub == "IR57", 7,
                                                                        if_else(sum(sig) > 0 & sub == "CP34", 8, 0))))))))) %>%
        mutate(sub = factor(sub, levels = c("IR9", "IR10", "IR16", "IR26", "IR28", "IR35", "IR57", "CP34"))) %>%
        arrange(sub)
      
        # write_csv #
        write_csv(sig_cing_elecs, path(here(), "figures", "anat_values", paste(file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR9"), path(here(), "figures", "anat_values", paste("IR9", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR10"), path(here(), "figures", "anat_values", paste("IR10", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR16"), path(here(), "figures", "anat_values", paste("IR16", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR26"), path(here(), "figures", "anat_values", paste("IR26", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR28"), path(here(), "figures", "anat_values", paste("IR28", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR35"), path(here(), "figures", "anat_values", paste("IR35", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "IR57"), path(here(), "figures", "anat_values", paste("IR57", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        write_csv(sig_cing_elecs %>% filter(sub == "CP34"), path(here(), "figures", "anat_values", paste("CP34", file_roi_name, band,  "sig_electrodes.csv", sep = "_")))
        
    
    
  
  
      ### filter to signifcant cingulate for each regressor and hemisphere ###
      predictors <- c("self_payoff", "other_payoff", "ineq_disadvent", "ineq_advent")
      hemispheres <- c("L", "R")
      epoch_list <- c("presentation", "choice")
      for(pred in predictors) {
        for(hemi in hemispheres) {
          for(epo in epoch_list) {
            sig_cing_elecs <- roi_band_regressions %>%
              filter(lat == hemi) %>%
              filter(epoch == epo) %>%
              filter(predictor == pred) %>%
              filter(values > 0) %>%
              select(sub, electrode, values, perm_p, epoch, predictor) %>%
              distinct() %>%
              mutate(sig = if_else(perm_p < PVAL, 1, 0)) %>%
              group_by(sub, electrode) %>%
              mutate(cing_pvals = if_else(sum(sig) > 0 & sub == "IR9", 1, 
                                      if_else(sum(sig) > 0 & sub == "IR10", 2, 
                                              if_else(sum(sig) > 0 & sub == "IR16", 3,
                                                      if_else(sum(sig) > 0 & sub == "IR26", 4,
                                                          if_else(sum(sig) > 0 & sub == "IR28", 5,
                                                              if_else(sum(sig) > 0 & sub == "IR35", 6,
                                                                    if_else(sum(sig) > 0 & sub == "IR57", 7,
                                                                          if_else(sum(sig) > 0 & sub == "CP34", 8, 0))))))))) %>%
              mutate(sub = factor(sub, levels = c("IR9", "IR10", "IR16", "IR26", "IR28", "IR35", "IR57", "CP34"))) %>%
              arrange(sub)
            
            # write_csv #
            write_csv(sig_cing_elecs, path(here(), "figures", "anat_values", paste(file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR9"), path(here(), "figures", "anat_values", paste("IR9", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR10"), path(here(), "figures", "anat_values", paste("IR10", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR16"), path(here(), "figures", "anat_values", paste("IR16", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR26"), path(here(), "figures", "anat_values", paste("IR26", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR28"), path(here(), "figures", "anat_values", paste("IR28", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR35"), path(here(), "figures", "anat_values", paste("IR35", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "IR57"), path(here(), "figures", "anat_values", paste("IR57", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            write_csv(sig_cing_elecs %>% filter(sub == "CP34"), path(here(), "figures", "anat_values", paste("CP34", file_roi_name, band, pred, hemi, epo, "sig_electrodes.csv", sep = "_")))
            
        }    
       }
     }
   }  
}  



```


```{r sig-regressions-all-regions}
# cingulate #
write_sig_roi_csvs(regression_results = regression_results, 
                   file_roi_name = "cingulate", 
                   freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), 
                   PVAL = .01)

# temporal gyrus #
write_sig_roi_csvs(regression_results = regression_results, 
                   file_roi_name = "temporal", 
                   freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), 
                   PVAL = .005)

# OFC #
write_sig_roi_csvs(regression_results = regression_results, 
                   file_roi_name = "ofc", 
                   freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), 
                   PVAL = .01)


# STS #
write_sig_roi_csvs(regression_results = regression_results, 
                   file_roi_name = "sts", 
                   freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), 
                   PVAL = .01)

# MFG #
write_sig_roi_csvs(regression_results = regression_results, 
                   file_roi_name = "mfg", 
                   freq_bands = c("delta", "theta", "alpha", "beta", "gamma", "hfa"), 
                   PVAL = .01)
  
```

```{r}


regression_results %>%
  filter(perm_p < .05) %>%
  ggplot(., aes(x = perm_p)) +
  geom_histogram(binwidth = .0005) +
    theme(panel.background = element_rect(fill = "white"))


```

