---
title: "Subject Exclusion"
author: "Brooke Staveland"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 12,  # set default width of figures
  fig.height = 6,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(lme4)
library(here)
library(fs)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))

## plotting helpers ##
getPalette = colorRampPalette(brewer.pal(12, "Set1"))

```


# Intro

This script determines which subjects/trials need to be excluded due to:

* missingness
* too fast response times
* missing check trials
* extreme side bias

```{r load-data}
## load in data ##

# path to beahvioral files #
path_to_raw_behave <- fs::path(here(), "../dg_behave_formatted")
path_to_behave_munge <- fs::path(here(), "munge", "combined_behavioral_data.csv")
path_to_behave_clean <- fs::path(here(), "munge", "clean_behavioral_data.csv")

# concactenate behavioral data #
load_behave_data(path_to_raw_behave)

# prep behavioral data #
prep_behave_data(path_to_behave_munge)

# load clean data #
behave_data <- read.csv(path_to_behave_clean)

```

```{r missingness}
## exclude subjects based on missingness ##

# look at different na maetrics to make sure they are the same #
numNAS <- behave_data %>%
  select(SID, round, RT, buttonpress_time, side_chosen) %>%
  mutate(rt_na = if_else(is.na(RT), 1, 0)) %>%
  mutate(rt_button = if_else(is.na(buttonpress_time), 1, 0)) %>%
  mutate(rt_side = if_else(is.na(side_chosen), 1, 0)) %>%
  mutate(na_equiv = rt_na + rt_button + rt_side)

# should be either 0 or 3, but there is a 1 column :( #
table(numNAS$na_equiv)

# where to look #
discrepantNA <- numNAS %>% filter(na_equiv == 1)

# ugh why is rt a NA when it has a button press time? #
behave_data %>%
  filter(SID == "DG_s09" & round > 112) %>%
  head(.)

rtCheck <- behave_data %>%
  mutate(manual_rt = buttonpress_time - choice_time) %>%
  mutate(rt_error = manual_rt - RT)

# error between them is rounding error low, so I will go with this to recover the one NA
max(rtCheck$rt_error, na.rm = T)

# modify behave_data #
behave_data <- behave_data %>%
  mutate(RT = buttonpress_time - choice_time) %>%
  mutate(rt_na = if_else(is.na(RT), 1, 0))
  

# now plot NAs By subject #
behave_data %>%
  ggplot(., aes(x = SID, y = rt_na, fill = SID)) +
  geom_col() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = getPalette(12)) +
  ylim(0, 40)
```
How many missing datapoints do we feel comfortable with? I want to exclude DG_s05 for this.


```{r speedy-rts}
## which subjects/trials had rts < 20ms? ##

behave_data <- behave_data %>%
  mutate(speedy_responses = if_else(RT < .20, 1, 0))

behave_data %>%
  ggplot(., aes(x = SID, y = speedy_responses, fill = SID)) +
  geom_col() +
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = getPalette(12))


```
Nothing, yay!

```{r check-trials}

## how many subjects missed trials where the better option for both self and other were better than 10? ##

behave_data <- behave_data %>%
    mutate(sanity_trials = if_else((L_self > 10 & L_other > 10 & L_self == L_other) | (R_self > 10 & R_other > 10 & R_self == R_other), 1, 0)) 

checkTrials <- behave_data %>%
    filter(sanity_trials == 1 & !is.na(side_chosen)) %>%
    mutate(best_side = if_else((L_self > 10 & L_other > 10), "Left", "Right")) %>%
    mutate(chose_better_side = if_else(best_side == side_chosen, "yes", "no")) %>%
    select(SID, round, L_self, L_other, R_self, R_other, side_chosen, best_side, chose_better_side) 

checkTrials %>%
  ggplot(., aes(x = SID, fill = SID, alpha = chose_better_side)) +
  geom_bar(position = "dodge") +
  theme(panel.background = element_rect(fill = "white")) +
  scale_fill_manual(values = getPalette(14)) +
  scale_alpha_discrete(range = c(.7, 1))

```
So person 5 should def go. 


11 and 10 seem like great starting subjects (w/ 11 slightly more messy)

also: DG_s11 -> IR35
      DG_s10 -> IR28
      
      
