---
title: "Load And Clean High Frequeny Band Activity"
author: "Brooke Staveland"
date: "3/21/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 12,  # set default width of figures
  fig.height <- 6,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "time_warp_preproc.R"))

## plotting helpers ##
# ggthemr("solarized")

# ## paralellization ##
# nCores <- 2
# registerDoParallel(nCores)

```


This script is loads, cleans, and merges the high frequency activity for both presentation-locked and choice-locked data. The results are csvs ready for input to the regression analysis.

```{r behave-prep}

# path to beahvioral files #
path_to_raw_behave <- fs::path(here(), "../dg_behave_formatted")
path_to_behave_munge <- fs::path(here(), "munge", "combined_behavioral_data.csv")
path_to_behave_clean <- fs::path(here(), "munge", "clean_behavioral_data.csv")

# concactenate behavioral data #
load_behave_data(path_to_raw_behave)

# prep behavioral data #
prep_behave_data(path_to_behave_munge)

# load clean data #
behave_data <- read.csv(path_to_behave_clean)

# filter to current subject #
behave_data_08 <- behave_data %>% filter(SID == "DG_s08")
behave_data_11 <- behave_data %>% filter(SID == "DG_s11")
behave_data_12 <- behave_data %>% filter(SID == "DG_s12")

# table(behave_data$ineq_advent_choice)
# table(behave_data_08$ineq_disadvent_choice)
# table(behave_data_11$ineq_disadvent_choice)
# table(behave_data_12$ineq_disadvent_choice)
```



```{r load-hfb-data-39}

## Load Presentation Data ##
# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR39_electrodes_presentation_locked_extended.csv")
file_path_to_hg_data <- path(here(), "munge", "IR39_hg_munge_presentation_locked_extended.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR39_elecs_of_interest_insula.csv")

# load data #
pres_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
pres_data <- pres_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

## Load Choice Data ##
# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR39_electrodes_choice_locked_cut_fixation.csv")
file_path_to_hg_data <- path(here(), "munge", "IR39_hg_munge_choice_locked_cut_fixation.csv")

# load data #
choice_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)

# filter to good electrodes #
choice_data <- choice_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

## Combine, Bins, and Baseline ##
cleaned_hfb_data <- time_warp_preproc(pres_data = pres_data,
                                      choice_data = choice_data,
                                      behave_data = behave_data_12)

# save it #
write.csv(cleaned_hfb_data, path(here(), "munge", "IR39", "hg_behave_time_warped_insula.csv"))


```

