---
title: "Load And Clean High Frequeny Band Activity"
author: "Brooke Staveland"
date: "3/21/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 12,  # set default width of figures
  fig.height <- 6,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
# ggthemr("solarized")

# ## paralellization ##
# nCores <- 2
# registerDoParallel(nCores)

```


This script is loads, cleans, and merges the high frequency activity for both presentation-locked and choice-locked data. The results are csvs ready for input to the regression analysis.

```{r behave-prep}

# path to beahvioral files #
path_to_raw_behave <- fs::path(here(), "../dg_behave_formatted")
path_to_behave_munge <- fs::path(here(), "munge", "combined_behavioral_data.csv")
path_to_behave_clean <- fs::path(here(), "munge", "clean_behavioral_data.csv")

# concactenate behavioral data #
load_behave_data(path_to_raw_behave)

# prep behavioral data #
prep_behave_data(path_to_behave_munge)

# load clean data #
behave_data <- read.csv(path_to_behave_clean)

# filter to current subject #
behave_data_08 <- behave_data %>% filter(SID == "DG_s08")
behave_data_11 <- behave_data %>% filter(SID == "DG_s11")
behave_data_12 <- behave_data %>% filter(SID == "DG_s12")

# table(behave_data$ineq_advent_choice)
# table(behave_data_08$ineq_disadvent_choice)
# table(behave_data_11$ineq_disadvent_choice)
# table(behave_data_12$ineq_disadvent_choice)
```

```{r load-hg-data-presentation-locked-35}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR35_electrodes_presentation_locked_extended.csv")
file_path_to_hg_data <- path(here(), "munge", "IR35_hg_munge_presentation_locked_extended.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR35_elecs_of_interest_insula.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# save baseline #
baseline_data <- hg_data[, 1:200]
baseline_data <- cbind(baseline_data, hg_data$electrodes, hg_data$trial)
write.csv(baseline_data, path(here(), "munge", "baseline_IR35.csv"))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, lWin = 150, lOver = 50, choice_locked = F)

# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_11, by.x = "trial", by.y = "round", all.x = T, all.y = F)
write.csv(hg_behave, path(here(), "munge", "IR35", "hg_behave_presentation_locked_extended_150_insula.csv"))

```


```{r load-hg-data-presentation-locked-19}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR19_electrodes_presentation_locked_extended.csv")
file_path_to_hg_data <- path(here(), "munge", "IR19_hg_munge_presentation_locked_extended.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR19_elecs_of_interest_insula.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# add behavioral data, remove bad trials, remove behavioral data again #
hg_data <- merge.data.frame(hg_data, behave_data_08, by.x = "trial", by.y = "round", all.x = T, all.y = F)
hg_data <- hg_data %>% filter(!is.na(RT)) %>% select(trial, electrodes, starts_with("time"))

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# save baseline #
baseline_data <- hg_data[, 1:200]
baseline_data <- cbind(baseline_data, hg_data$electrodes, hg_data$trial)
write.csv(baseline_data, path(here(), "munge", "baseline_IR19.csv"))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, lWin = 150, lOver = 50, choice_locked = F)

# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_08, by.x = "trial", by.y = "round", all.x = T, all.y = F)
# clean any missing RTs #
hg_behave <- hg_behave %>% filter(!is.na(RT))
# save it #
write.csv(hg_behave, path(here(), "munge", "IR19", "hg_behave_presentation_locked_extended_150_insula.csv"))

```


```{r load-hg-data-presentation-locked-39}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR39_electrodes_presentation_locked_extended.csv")
file_path_to_hg_data <- path(here(), "munge", "IR39_hg_munge_presentation_locked_extended.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR39_elecs_of_interest_insula.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# # save baseline #
# baseline_data <- hg_data[, 1:200]
# baseline_data <- cbind(baseline_data, hg_data$electrodes, hg_data$trial)
# write.csv(baseline_data, path(here(), "munge", "baseline_IR39.csv"))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, lWin = 150, lOver = 50, choice_locked = F)

# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_12, by.x = "trial", by.y = "round", all.x = T, all.y = F)
# clean any missing RTs #
hg_behave <- hg_behave %>% filter(!is.na(RT))
# save it #
write.csv(hg_behave, path(here(), "munge", "IR39", "hg_behave_presentation_locked_extended_100_insula.csv"))

```

```{r load-hg-data-choice-locked-35}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR35_electrodes_choice_locked_cut_fixation.csv")
file_path_to_hg_data <- path(here(), "munge", "IR35_hg_munge_choice_locked_cut_fixation.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR35_elecs_of_interest_insula.csv")
file_path_to_baseline <- path(here(), "munge", "baseline_IR35.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, baseline_csv = file_path_to_baseline, lWin = 150, lOver = 50, choice_locked = T)

# create temp data for visualiztion #
half_index <- sample(1:228, 114)
hg_eda <- hg_clean %>% filter(trial %in% half_index)


# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_11, by.x = "trial", by.y = "round", all.x = T, all.y = F)
# clean any missing RTs #
hg_behave <- hg_behave %>% filter(!is.na(RT))
# save it #
write.csv(hg_behave, path(here(), "munge", "IR35", "hg_behave_choice_locked_cut_fixation_150_insula.csv"))

```

```{r load-hg-data-choice-locked-19}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR19_electrodes_choice_locked_cut_fixation.csv")
file_path_to_hg_data <- path(here(), "munge", "IR19_hg_munge_choice_locked_cut_fixation.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR19_elecs_of_interest_insula.csv")
file_path_to_baseline <- path(here(), "munge", "baseline_IR19.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# add behavioral data, remove bad trials, remove behavioral data again #
hg_data <- merge.data.frame(hg_data, behave_data_08, by.x = "trial", by.y = "round", all.x = T, all.y = F)
hg_data <- hg_data %>% filter(!is.na(RT)) %>% select(trial, electrodes, starts_with("time"))

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, baseline_csv = file_path_to_baseline, lWin = 150, lOver = 50, choice_locked = T)

# create temp data for visualiztion #
half_index <- sample(1:228, 114)
hg_eda <- hg_clean %>% filter(trial %in% half_index)


# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_08, by.x = "trial", by.y = "round", all.x = T, all.y = F)
# clean any missing RTs #
hg_behave <- hg_behave %>% filter(!is.na(RT))
# save it #
write.csv(hg_behave, path(here(), "munge", "IR19", "hg_behave_choice_locked_cut_fixation_150_insula.csv"))




```


```{r load-hg-data-choice-locked-39}

# necessary paths #
file_path_to_electrode_names <- path(here(), "munge", "IR39_electrodes_choice_locked_cut_fixation.csv")
file_path_to_hg_data <- path(here(), "munge", "IR39_hg_munge_choice_locked_cut_fixation.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR39_elecs_of_interest_insula.csv")
file_path_to_baseline <- path(here(), "munge", "baseline_IR39.csv")

# load data #
hg_data <- load_high_gamma_data(file_path_to_hg_data, file_path_to_electrode_names)
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))

# average and baseline #
hg_clean <- rolling_window_and_baseline(hg_data, baseline_csv = file_path_to_baseline, lWin = 150, lOver = 50, choice_locked = T)

# create temp data for visualiztion #
half_index <- sample(1:228, 114)
hg_eda <- hg_clean %>% filter(trial %in% half_index)


# with behavior #
hg_behave <- merge.data.frame(hg_clean, behave_data_12, by.x = "trial", by.y = "round", all.x = T, all.y = F)
# clean any missing RTs #
hg_behave <- hg_behave %>% filter(!is.na(RT))
# save it #
write.csv(hg_behave, path(here(), "munge", "IR39", "hg_behave_choice_locked_cut_fixation_150_insula.csv"))

```
