---
title: "Visualize Results - Wavelets"
author: "Brooke Staveland"
date: "6/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 12,  # set default width of figures
  fig.height <- 6,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- TRUE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
# ggthemr("solarized")

## paralellization ##
nCores <- 2
registerDoParallel(nCores)

```

# Dictator Game Regression Results

This analysis script visualizes the output of the permuted regressions.

## Load Presentation

Load and prep presentation-locked results for all subjects.

```{r concatenate-results-presentation}

### any subject general vars ###
spec_vars <- c("*", "*")
abs_beta_val <- T
reg_name_one <- "self_diff"
reg_name_two <- "other_diff"
regions_to_combine <- c("Insula")
  
## IR39 ##

# combine different csvs #
hfa_presentation_results_39 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-wavelets",
                                           sub = "IR39",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR39", "wavelets", "insula"),
                                           absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR39", "hg_behave_presentation_locked_extended_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# run_filtered_anova(results = presentation_results_39,
#                    brain_behave_data = hg_behave,
#                    sub = "IR39",
#                    region_name = "All",
#                    reg_name_one = reg_name_one,
#                    reg_name_two = reg_name_two,
#                    all_results = T,
#                    type = "pres-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_pres_results_for_plots_39 <- read.csv(fs::path(here(), "results", "IR39", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_pres_results_for_plots_39 <- read.csv(fs::path(here(), "results", "IR39", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_two, ".csv")))


## IR35 ##

# combine different csvs #
hfa_presentation_results_35 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-pres-locked-wavelets", 
                                           sub = "IR35", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR35", "wavelets", "insula"), 
                                           absBeta = abs_beta_val)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR35", "hg_behave_presentation_locked_extended_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# run_filtered_anova(results = presentation_results_35, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR35", 
#                    region_name = "All", 
#                    all_results = T, 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    type = "pres-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_pres_results_for_plots_35 <- read.csv(fs::path(here(), "results", "IR35", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_pres_results_for_plots_35 <- read.csv(fs::path(here(), "results", "IR35", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR19 ##

# combine different csvs #
hfa_presentation_results_19 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-pres-locked-wavelets", 
                                           sub = "IR19", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR19", "wavelets", "insula"), 
                                           absBeta = abs_beta_val)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR19", "hg_behave_presentation_locked_extended_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR19 has weird elec names
# run_filtered_anova(results = presentation_results_19, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR19", 
#                    region_name = "All", 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    all_results = T, 
#                    type = "pres-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_pres_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_pres_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR16 ##

# combine different csvs #
presentation_results_16 <- compile_results(regions = regions_to_combine,
                                           type = "pres-locked-wavelets",
                                           sub = "IR16",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR16", "insula"),
                                           absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR16", "hg_behave_presentation_locked_extended_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR16 has weird elec names
# run_filtered_anova(results = presentation_results_16,
#                    brain_behave_data = hg_behave,
#                    sub = "IR16",
#                    region_name = "All",
#                    reg_name_one = reg_name_one,
#                    reg_name_two = reg_name_two,
#                    all_results = T,
#                    type = "pres-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_pres_results_for_plots_16 <- read.csv(fs::path(here(), "results", "IR16", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_pres_results_for_plots_16 <- read.csv(fs::path(here(), "results", "IR16", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR57 ##

# combine different csvs #
presentation_results_57 <- compile_results(regions = regions_to_combine,
                                           type = "pres-locked-wavelets",
                                           sub = "IR57",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR57", "insula"),
                                           absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR57", "hg_behave_presentation_locked_extended_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR16 has weird elec names
# run_filtered_anova(results = presentation_results_57,
#                    brain_behave_data = hg_behave,
#                    sub = "IR57",
#                    region_name = "All",
#                    reg_name_one = reg_name_one,
#                    reg_name_two = reg_name_two,
#                    all_results = T,
#                    type = "pres-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_pres_results_for_plots_57 <- read.csv(fs::path(here(), "results", "IR57", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_pres_results_for_plots_57 <- read.csv(fs::path(here(), "results", "IR57", paste0(region_name, "_pres-locked_insula_anova_results_", reg_name_two, ".csv")))


```


## Load Choice

Load and prep choice-locked results for all subjects.

```{r concatenate-results-choice}

### any subject general vars ###
spec_vars <- c("*", "*")
abs_beta_val <- F
reg_name_one <- "self_diff"
reg_name_two <- "other_diff"
regions_to_combine <- c("All_Regions")
  
## IR39 ##

# combine different csvs #
choice_results_39_all <- compile_results(regions = regions_to_combine,
                                           type = "choice-locked",
                                           sub = "IR39",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR39"),
                                           absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR39", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# run_filtered_anova(results = choice_results_39,
#                    brain_behave_data = hg_behave,
#                    sub = "IR39",
#                    region_name = "All",
#                    reg_name_one = reg_name_one,
#                    reg_name_two = reg_name_two,
#                    all_results = T,
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_39 <- read.csv(fs::path(here(), "results", "IR39", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_39 <- read.csv(fs::path(here(), "results", "IR39", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))


## IR35 ##

# combine different csvs #
regions_to_combine <- c("All_Regions")
choice_results_35_all <- compile_results(regions = regions_to_combine, 
                                     type = "choice-locked", 
                                     sub = "IR35", 
                                     spec_vars = spec_vars, 
                                     path = path(here(), "results", "IR35"), 
                                     absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR35", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# run_filtered_anova(results = choice_results_35, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR35", 
#                    region_name = "All", 
#                    all_results = T, 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_35 <- read.csv(fs::path(here(), "results", "IR35", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_35 <- read.csv(fs::path(here(), "results", "IR35", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR19 ##

# combine different csvs #
regions_to_combine <- c("All_Regions")
choice_results_19_all <- compile_results(regions = regions_to_combine, 
                                     type = "choice-locked", 
                                     sub = "IR19", 
                                     spec_vars = spec_vars, 
                                     path = path(here(), "results", "IR19"), 
                                     absBeta = F)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR19", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR19 has weird elec names
# run_filtered_anova(results = choice_results_19, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR19", 
#                    region_name = "All", 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    all_results = T, 
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR16 ##

# combine different csvs #
regions_to_combine <- c("Insula")
choice_results_16 <- compile_results(regions = regions_to_combine, 
                                     type = "choice-locked", 
                                     sub = "IR16", 
                                     spec_vars = spec_vars, 
                                     path = path(here(), "results", "IR16", "insula"), 
                                     absBeta = abs_beta_val)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR16", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR16 has weird elec names
# run_filtered_anova(results = choice_results_16, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR16", 
#                    region_name = "All", 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    all_results = T, 
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_16 <- read.csv(fs::path(here(), "results", "IR16", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_16 <- read.csv(fs::path(here(), "results", "IR16", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))

## IR57 ##

# combine different csvs #
regions_to_combine <- c("Insula")
choice_results_57 <- compile_results(regions = regions_to_combine, 
                                     type = "choice-locked", 
                                     sub = "IR57", 
                                     spec_vars = spec_vars, 
                                     path = path(here(), "results", "IR57", "insula"), 
                                     absBeta = abs_beta_val)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR57", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR16 has weird elec names
# run_filtered_anova(results = choice_results_57, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR57", 
#                    region_name = "All", 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    all_results = T, 
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_57 <- read.csv(fs::path(here(), "results", "IR57", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_57 <- read.csv(fs::path(here(), "results", "IR57", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))

```

## plotting functions

```{r plotting-functions}
ggthemr::ggthemr("pale", layout = "plain")
getPalette = colorRampPalette(brewer.pal(10, "Set1"))

ineq_plots <- function(df, title) {
# plots the bar plots of dif in R2 for inequity  
df %>%
    ungroup() %>%
    mutate(sig = if_else(perm_p < 0.05 & anova_p < 0.01, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    mutate(bin = as.numeric(gsub("time_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes( x = bin, y = diff_adj_r2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Difference in Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)
  
}

ineq_plots_choice <- function(df, title) {
# plots the bar plots of dif in R2 for inequity  
df %>%
    ungroup() %>%
    mutate(sig = if_else(perm_p < 0.05 & anova_p < 0.01, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes( x = bin, y = diff_adj_r2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Difference in Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)
  
}

active_elec_plots <- function(df, var, title) {
  df %>%
    filter(predictor == var) %>%
    mutate(sig = if_else(perm_p < 0.0125 & p < 0.05, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    # mutate(bin = factor(bin, levels = colnames(hg_data)[4:38])) %>%
    ggplot(., aes( x = bin, y = R2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)

}

combined_active_plots <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    # filter(!predictor %in% c("ineq_advent", "ineq_disadvent")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor = relevel(factor(predictor), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("time_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor, color = predictor)) + 
    geom_col(alpha = .5) + 
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}

combined_active_plots_choice <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    # filter(!predictor %in% c("ineq_advent", "ineq_disadvent")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor = relevel(factor(predictor), ref = "Insig")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor, color = predictor)) + 
    geom_col(alpha = .5) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}

combined_active_plots_for_talk <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    filter(!predictor %in% c("ineq_advent", "ineq_disadvent", "self_diff", "other_diff")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor_case = if_else(grepl("other|disadvent", predictor), "ther", "elf")) %>%
    mutate(predictor_case = if_else(bin_sig == 0, "Insig", as.character(predictor_case))) %>%
    mutate(predictor_case = relevel(factor(predictor_case), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("time_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor_case, color = predictor_case)) + 
    geom_col(alpha = .5) + 
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Regressor", color = "Regressor") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject))
}



combined_active_plots_choice_for_talk <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    # filter(!predictor %in% c("ineq_advent", "ineq_disadvent")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor_case = if_else(grepl("other|disadvent", predictor), "other", "self")) %>%
    mutate(predictor_case = if_else(bin_sig == 0, "Insig", as.character(predictor_case))) %>%
    mutate(predictor_case = relevel(factor(predictor_case), ref = "Insig")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor_case, color = predictor_case)) + 
    geom_col(alpha = .5) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(8))) +
      scale_color_manual(values = c("grey", getPalette(8))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Regressor", color = "Regressor") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject))
}

beta_plots_all_subjects <- function(df, sig_thresh, nrows, subject, vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone")){
  df %>%
    filter(predictor %in% vars) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(predictor_sig = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor_sig = relevel(factor(predictor_sig, levels = c("Insig", vars)), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("time_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x = bin, y= Beta, group = predictor)) +
    geom_line(color = "grey", alpha = .3) +
    geom_point(aes(color = predictor_sig)) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9)), drop = F) +
      scale_color_manual(values = c("grey", getPalette(9)), drop = F) +
      labs(y = "Beta", x = "Bins",  color = "Regressor") +
    facet_wrap(~electrode, nrow = nrows) +
    ggtitle(paste0(subject))
}

beta_plots_all_subjects_choice <- function(df, sig_thresh, nrows, subject, vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone")){
  df %>%
    filter(predictor %in% vars) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(predictor_sig = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor_sig = relevel(factor(predictor_sig, levels = c("Insig", vars)), ref = "Insig")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x = bin, y= Beta, group = predictor)) +
    geom_line(color = "grey", alpha = .3) +
    geom_point(aes(color = predictor_sig)) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9)), drop = F) +
      scale_color_manual(values = c("grey", getPalette(9)), drop = F) +
      labs(y = "Beta", x = "Bins",  color = "Regressor") +
    facet_wrap(~electrode, nrow = nrows) +
    ggtitle(paste0(subject))
}
```

## Presentation Results

```{r presentation-results}

## exclude mistaken regions!! ###
hfa_presentation_results_35 <- hfa_presentation_results_35 %>% filter(electrode != "LAC10-LAC11" & electrode != "LAC9-LAC10" & electrode != "LIN9-LIN10")
hfa_presentation_results_19 <- hfa_presentation_results_19 %>%
  mutate(electrode = gsub("POL ", "", electrode)) %>%
  mutate(electrode = gsub(" POL", "", electrode)) %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
  mutate(electrode = gsub("-Ref", "", electrode)) %>% 
  filter(electrode != "LIN10-LIN11" & electrode != "LIN12-LIN13" & electrode != "LIN11-LIN12" & electrode != "LIN9-LIN10" & electrode != "RIN10-RIN11" & electrode != "RIN11-RIN12" & electrode != "RIN12-RIN13" & electrode != "RIN9-RIN10")

plot_39_005 <- combined_active_plots(presentation_results_39, "IR39 ~ Presentation", 2, sig_thresh = 0.005)
plot_35_005 <- combined_active_plots(hfa_presentation_results_35, "IR35 ~ Presentation", 2, sig_thresh = 0.01)
plot_19_005 <- combined_active_plots(hfa_presentation_results_19, "IR19 ~ Presentation", 3, sig_thresh = 0.01)

ggsave(filename = paste0(path(here(), './figures/plot_39_005.png')),
     device = "png",
     width = 20,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(plot_39_05)) )

ggsave(filename = paste0(path(here(), './figures/plot_35_05.png')),
     device = "png",
     width = 20,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(plot_35_05)) )

ggsave(filename = paste0(path(here(), './figures/plot_19_05.png')),
     device = "png",
     width = 20,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(plot_19_05)) )

plot_39_005
plot_35_005
plot_19_005
```

```{r pres-for-talk-results-combine-by-region}

getPalette = colorRampPalette(brewer.pal(9, "Set1"))


## exclude mistaken regions!! ###
presentation_results_35 <- presentation_results_35 %>% filter(electrode != "LAC10-LAC11" & electrode != "LAC9-LAC10" & electrode != "LIN9-LIN10")
presentation_results_19 <- presentation_results_19 %>% filter(electrode != "LIN10-Ref-LIN11-Ref" & electrode != "LIN12-Ref-LIN13-Ref" & electrode != "LIN11-Ref-LIN12-Ref" & electrode != "LIN9-Ref-LIN10-Ref" & electrode != "RIN10-Ref-RIN11-Ref" & electrode != "RIN11-Ref-RIN12-Ref" & electrode != "RIN12-Ref-RIN13-Ref" & electrode != "RIN9-Ref-RIN10-Ref")
presentation_results_57 <- presentation_results_57 %>% filter(electrode != "RTI9-RTI10" & electrode != "RIN9-RIN10" & electrode != "LIN9-LIN10" & electrode != "LTI9-LTI10")


presentation_results_39_with_elec_info <- presentation_results_39 %>%
  mutate(elec_region = if_else(electrode == "LIN1-LIN2", "blue", 
                              if_else(electrode == "LOF3-LOF4", "purple",
                                      if_else(electrode == "LOF4-LOF5", "purple",
                                              if_else(electrode == "LOF5-LOF6", "purple",
                                                      if_else(electrode == "RAM5-RAM6", "yellow",
                                                              if_else(electrode == "RAM6-RAM7", "yellow",
                                                                      if_else(electrode == "RAM7-RAM8", "yellow",
                                                                              if_else(electrode == "RIN1-RIN2", "green",
                                                                                      if_else(electrode == "RIN2-RIN3", "blue",
                                                                                              if_else(electrode == "RIN3-RIN4", "blue", "help")))))))))))

presentation_results_39_with_elec_info <- presentation_results_39_with_elec_info %>% mutate(electrode = paste0(electrode, "-39"))

presentation_results_19_with_elec_info <- presentation_results_19 %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
  mutate(electrode = gsub("-Ref", "-19", electrode)) %>%
  mutate(elec_region = if_else(electrode == "LAM8-LAM9-19", "yellow", 
                              if_else(electrode == "LAM9-LAM10-19", "yellow",
                                      if_else(electrode == "LIN1-LIN2-19", "pink",
                                              if_else(electrode == "LIN2-LIN3-19", "green",
                                                      if_else(electrode == "LIN3-LIN4-19", "blue",
                                                              if_else(electrode == "LIN4-LIN5-19", "blue",
                                                                      if_else(electrode == "RAM7-RAM8-19", "yellow",
                                                                              if_else(electrode == "RAM8-RAM9-19", "yellow",
                                                                                      if_else(electrode == "RIN1-RIN2-19", "blue",
                                                                                              if_else(electrode == "RIN2-RIN3-19", "green",
                                                                                                      if_else(electrode == "RIN3-RIN4-19", "green",
                                                                                                             if_else(electrode == "RIN4-RIN5-19", "blue",
                                                                                                                     if_else(electrode == "RIN5-RIN6-19", "blue","help"))))))))))))))


presentation_results_35_with_elec_info <- presentation_results_35 %>%
  mutate(elec_region = if_else(electrode == "LIN1-LIN2", "yellow", 
                              if_else(electrode == "LIN2-LIN3", "pink",
                                      if_else(electrode == "LIN3-LIN4", "green",
                                              if_else(electrode == "LIN4-LIN5", "blue",
                                                      if_else(electrode == "RIN1-RIN2", "yellow",
                                                              if_else(electrode == "RIN2-RIN3", "pink",
                                                                      if_else(electrode == "RIN3-RIN4", "blue", "help"))))))))

presentation_results_35_with_elec_info <- presentation_results_35_with_elec_info %>% mutate(electrode = paste0(electrode, "-35"))

# IR57 #
presentation_results_57_with_elec_info <- presentation_results_57 %>%
  mutate(elec_region = if_else(electrode == "LAM4-LAM5", "purple", 
                              if_else(electrode == "LIN1-LIN2", "pink",
                                      if_else(electrode == "LIN2-LIN3", "green",
                                              if_else(electrode == "LIN3-LIN4", "green",
                                                      if_else(electrode == "LIN4-LIN5", "blue",
                                                              if_else(electrode == "LTI1-LTI2", "blue",
                                                                      if_else(electrode == "LTI2-LTI3", "blue",
                                                                              if_else(electrode == "RIN1-RIN2", "yellow",
                                                                                      if_else(electrode == "RIN2-RIN3", "yellow",
                                                                                              if_else(electrode == "RIN3-RIN4", "pink",
                                                                                                      if_else(electrode == "RIN4-RIN5", "green",
                                                                                                             if_else(electrode == "RIN4-RIN5", "blue",
                                                                                                                     if_else(electrode == "RIN5-RIN6", "blue",
                                                                                                                             if_else(electrode == "RIN6-RIN7", "blue", 
                                                                                                                                     if_else(electrode == "RTI1-RTI2", "green",
                                                                                                                                             if_else(electrode == "RTI2-RTI3", "green",
                                                                                                                                                     if_else(electrode == "RTI3-RTI4", "green", "help")))))))))))))))))) %>%
  mutate(electrode = paste0(electrode, "-57"))


# IR16 #
presentation_results_16_with_elec_info <- presentation_results_16 %>%
  mutate(electrode = gsub("POL ", "", electrode)) %>%
  mutate(electrode = gsub(" POL", "", electrode)) %>%
  mutate(electrode = gsub("-Ref", "", electrode)) %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
  mutate(elec_region = if_else(electrode == "LAM3-LAM4", "yellow", 
                              if_else(electrode == "LAM4-LAM5", "yellow",
                                      if_else(electrode == "LIN1-LIN2", "pink",
                                              if_else(electrode == "LIN2-LIN3", "green",
                                                      if_else(electrode == "LIN3-LIN4", "blue",
                                                              if_else(electrode == "LIN4-LIN5", "blue",
                                                                      if_else(electrode == "LIN5-LIN6", "yellow","help")))))))) %>%
  
  mutate(electrode = paste0(electrode, "-16"))


```


```{r pres-results-combine-subject}

# combine them #
presentation_results_full <- rbind(#presentation_results_19_with_elec_info, 
                                   presentation_results_35_with_elec_info, 
                                   presentation_results_39_with_elec_info)
                                 #  presentation_results_57_with_elec_info,
                                  # presentation_results_16_with_elec_info)
                                 


beta_plots_all_subjects(presentation_results_full, 
                               sig_thresh = 0.01, 
                               6, 
                               "Presentation ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))


```

```{r pres-results-broken-down-by-roi}}


blue_presentation <- presentation_results_full %>% filter(elec_region == "blue")
yellow_presentation <- presentation_results_full %>% filter(elec_region == "yellow")
pink_presentation <- presentation_results_full %>% filter(elec_region == "pink")
purple_presentation <- presentation_results_full %>% filter(elec_region == "purple")
green_presentation <- presentation_results_full %>% filter(elec_region == "green")

b_p <- beta_plots_all_subjects(blue_presentation, 
                               sig_thresh = 0.01, 
                               5, 
                               "Presentation ~ Blue ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

y_p <- beta_plots_all_subjects(yellow_presentation, 
                               sig_thresh = 0.01, 
                               5, 
                               "Presentation ~ Yellow ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

g_p <- beta_plots_all_subjects(green_presentation, 
                               sig_thresh = 0.01, 
                               4, 
                               "Presentation ~ Green ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

purp_p <- beta_plots_all_subjects(purple_presentation, 
                               sig_thresh = 0.01, 
                               2, 
                               "Presentation ~ Purple ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

pi_p <- beta_plots_all_subjects(pink_presentation, 
                               sig_thresh = 0.01, 
                               3, 
                               "Presentation ~ Pink ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))


ggsave(filename = paste0(path(here(), './figures/wavelet/purple_pres.png')),
     device = "png",
     width = 25,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(purp_p)) )

ggsave(filename = paste0(path(here(), './figures/wavelet/pink_pres.png')),
     device = "png",
     width = 25,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(pi_p)) )

ggsave(filename = paste0(path(here(), './figures/wavelet/green_pres.png')),
     device = "png",
     width = 25,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(g_p)) )

ggsave(filename = paste0(path(here(), './figures/wavelet/yellow_pres.png')),
     device = "png",
     width = 25,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(y_p)) )


ggsave(filename = paste0(path(here(), './figures/wavelet/blue_pres.png')),
     device = "png",
     width = 30,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(b_p)) )

```

## Choice Resutls

```{r choice-results-combine-by-region}

getPalette = colorRampPalette(brewer.pal(9, "Set1"))


## exclude mistaken regions!! ###
choice_results_35 <- choice_results_35 %>% filter(electrode != "LAC10-LAC11" & electrode != "LAC9-LAC10" & electrode != "LIN9-LIN10")
choice_results_19 <- choice_results_19 %>% filter(electrode != "LIN10-Ref-LIN11-Ref" & electrode != "LIN12-Ref-LIN13-Ref" & electrode != "LIN11-Ref-LIN12-Ref" & electrode != "LIN9-Ref-LIN10-Ref" & electrode != "RIN10-Ref-RIN11-Ref" & electrode != "RIN11-Ref-RIN12-Ref" & electrode != "RIN12-Ref-RIN13-Ref" & electrode != "RIN9-Ref-RIN10-Ref")
choice_results_57 <- choice_results_57 %>% filter(electrode != "RTI9-RTI10" & electrode != "RIN9-RIN10" & electrode != "LIN9-LIN10" & electrode != "LTI9-LTI10")

# IR39 #
choice_results_39_with_elec_info <- choice_results_39 %>%
  mutate(elec_region = if_else(electrode == "LIN1-LIN2", "blue", 
                              if_else(electrode == "LOF3-LOF4", "purple",
                                      if_else(electrode == "LOF4-LOF5", "purple",
                                              if_else(electrode == "LOF5-LOF6", "purple",
                                                      if_else(electrode == "RAM5-RAM6", "yellow",
                                                              if_else(electrode == "RAM6-RAM7", "yellow",
                                                                      if_else(electrode == "RAM7-RAM8", "yellow",
                                                                              if_else(electrode == "RIN1-RIN2", "green",
                                                                                      if_else(electrode == "RIN2-RIN3", "blue",
                                                                                              if_else(electrode == "RIN3-RIN4", "blue", "help")))))))))))

choice_results_39_with_elec_info <- choice_results_39_with_elec_info %>% mutate(electrode = paste0(electrode, "-39"))

# IR19 #
choice_results_19_with_elec_info <- choice_results_19 %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
  mutate(electrode = gsub("-Ref", "-19", electrode)) %>%
  mutate(elec_region = if_else(electrode == "LAM8-LAM9-19", "yellow", 
                              if_else(electrode == "LAM9-LAM10-19", "yellow",
                                      if_else(electrode == "LIN1-LIN2-19", "pink",
                                              if_else(electrode == "LIN2-LIN3-19", "green",
                                                      if_else(electrode == "LIN3-LIN4-19", "blue",
                                                              if_else(electrode == "LIN4-LIN5-19", "blue",
                                                                      if_else(electrode == "RAM7-RAM8-19", "yellow",
                                                                              if_else(electrode == "RAM8-RAM9-19", "yellow",
                                                                                      if_else(electrode == "RIN1-RIN2-19", "blue",
                                                                                              if_else(electrode == "RIN2-RIN3-19", "green",
                                                                                                      if_else(electrode == "RIN3-RIN4-19", "green",
                                                                                                             if_else(electrode == "RIN4-RIN5-19", "blue",
                                                                                                                     if_else(electrode == "RIN5-RIN6-19", "blue","help"))))))))))))))


# IR35 #
choice_results_35_with_elec_info <- choice_results_35 %>%
  mutate(elec_region = if_else(electrode == "LIN1-LIN2", "yellow", 
                              if_else(electrode == "LIN2-LIN3", "pink",
                                      if_else(electrode == "LIN3-LIN4", "green",
                                              if_else(electrode == "LIN4-LIN5", "blue",
                                                      if_else(electrode == "RIN1-RIN2", "yellow",
                                                              if_else(electrode == "RIN2-RIN3", "pink",
                                                                      if_else(electrode == "RIN3-RIN4", "blue", "help"))))))))

choice_results_35_with_elec_info <- choice_results_35_with_elec_info %>% mutate(electrode = paste0(electrode, "-35"))

# IR57 #
choice_results_57_with_elec_info <- choice_results_57 %>%
  mutate(elec_region = if_else(electrode == "LAM4-LAM5", "purple", 
                              if_else(electrode == "LIN1-LIN2", "pink",
                                      if_else(electrode == "LIN2-LIN3", "green",
                                              if_else(electrode == "LIN3-LIN4", "green",
                                                      if_else(electrode == "LIN4-LIN5", "blue",
                                                              if_else(electrode == "LTI1-LTI2", "blue",
                                                                      if_else(electrode == "LTI2-LTI3", "blue",
                                                                              if_else(electrode == "RIN1-RIN2", "yellow",
                                                                                      if_else(electrode == "RIN2-RIN3", "yellow",
                                                                                              if_else(electrode == "RIN3-RIN4", "pink",
                                                                                                      if_else(electrode == "RIN4-RIN5", "green",
                                                                                                             if_else(electrode == "RIN4-RIN5", "blue",
                                                                                                                     if_else(electrode == "RIN5-RIN6", "blue",
                                                                                                                             if_else(electrode == "RIN6-RIN7", "blue", 
                                                                                                                                     if_else(electrode == "RTI1-RTI2", "green",
                                                                                                                                             if_else(electrode == "RTI2-RTI3", "green",
                                                                                                                                                     if_else(electrode == "RTI3-RTI4", "green", "help")))))))))))))))))) %>%
  mutate(electrode = paste0(electrode, "-57"))


# IR16 #
choice_results_16_with_elec_info <- choice_results_16 %>%
  mutate(electrode = gsub("POL ", "", electrode)) %>%
  mutate(electrode = gsub(" POL", "", electrode)) %>%
  mutate(electrode = gsub("-Ref", "", electrode)) %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>%
  mutate(elec_region = if_else(electrode == "LAM3-LAM4", "yellow", 
                              if_else(electrode == "LAM4-LAM5", "yellow",
                                      if_else(electrode == "LIN1-LIN2", "pink",
                                              if_else(electrode == "LIN2-LIN3", "green",
                                                      if_else(electrode == "LIN3-LIN4", "blue",
                                                              if_else(electrode == "LIN4-LIN5", "blue",
                                                                      if_else(electrode == "LIN5-LIN6", "yellow","help")))))))) %>%
  
  mutate(electrode = paste0(electrode, "-16"))

```

```{r choice-results-combine-subject}


# combine them #
choice_results_full <- rbind(choice_results_19_with_elec_info, 
                             choice_results_35_with_elec_info, 
                             choice_results_39_with_elec_info, 
                             choice_results_57_with_elec_info, 
                             choice_results_16_with_elec_info)


left_39 <- choice_results_39_all %>% filter(grepl("^L", electrode))
right_39 <- choice_results_39_all %>% filter(grepl("^R", electrode))

left_19 <- choice_results_19_all %>%
  mutate(electrode = gsub("POL ", "", electrode)) %>%
  mutate(electrode = gsub(" POL", "", electrode)) %>%
  mutate(electrode = gsub("-Ref", "", electrode)) %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>% 
  filter(grepl("^L", electrode))

right_19 <- choice_results_19_all %>%
  mutate(electrode = gsub("POL ", "", electrode)) %>%
  mutate(electrode = gsub(" POL", "", electrode)) %>%
  mutate(electrode = gsub("-Ref", "", electrode)) %>%
  mutate(electrode = gsub("-Ref-", "-", electrode)) %>% 
  filter(grepl("^R", electrode))

left_35 <- choice_results_35_all %>% filter(grepl("^L", electrode))
right_35 <- choice_results_35_all %>% filter(grepl("^R", electrode))

beta_plots_all_subjects_choice(left_39, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Left ~ IR39",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))

beta_plots_all_subjects_choice(right_39, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Right ~ IR39",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))

beta_plots_all_subjects_choice(left_19, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Left ~ IR19",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))

beta_plots_all_subjects_choice(right_19, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Right ~ IR19",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))

beta_plots_all_subjects_choice(left_35, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Left ~ IR35",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))

beta_plots_all_subjects_choice(right_35, 
                               sig_thresh = 0.01, 
                               6, 
                               "Choice ~ Right ~ IR35",
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone", "ineq_advent", "ineq_disadvent"))


```


```{r choice-results-broken-down-by-roi}


blue_choice <- choice_results_full %>% filter(elec_region == "blue")
yellow_choice <- choice_results_full %>% filter(elec_region == "yellow")
pink_choice <- choice_results_full %>% filter(elec_region == "pink")
purple_choice <- choice_results_full %>% filter(elec_region == "purple")
green_choice <- choice_results_full %>% filter(elec_region == "green")

b_p <- beta_plots_all_subjects_choice(blue_choice, 
                               sig_thresh = 0.01, 
                               5, 
                               "Choice ~ Blue ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

y_p <- beta_plots_all_subjects_choice(yellow_choice, 
                               sig_thresh = 0.01, 
                               5, 
                               "Choice ~ Yellow ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

g_p <- beta_plots_all_subjects_choice(green_choice, 
                               sig_thresh = 0.01, 
                               4, 
                               "Choice ~ Green ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

purp_p <- beta_plots_all_subjects_choice(purple_choice, 
                               sig_thresh = 0.01, 
                               2, 
                               "Choice ~ Purple ~All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))

pi_p <- beta_plots_all_subjects_choice(pink_choice, 
                               sig_thresh = 0.01, 
                               3, 
                               "Choice ~ Pink ~ All Subjects", 
                               vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone"))


ggsave(filename = paste0(path(here(), './figures/purple_choice.png')),
     device = "png",
     width = 25,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(purp_p)) )

ggsave(filename = paste0(path(here(), './figures/pink_choice.png')),
     device = "png",
     width = 25,
     height = 10,
     units = "cm",
     dpi = 200,
     plot =  print(plot(pi_p)) )

ggsave(filename = paste0(path(here(), './figures/green_choice.png')),
     device = "png",
     width = 25,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(g_p)) )

ggsave(filename = paste0(path(here(), './figures/yellow_choice.png')),
     device = "png",
     width = 25,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(y_p)) )


ggsave(filename = paste0(path(here(), './figures/blue_choice.png')),
     device = "png",
     width = 30,
     height = 15,
     units = "cm",
     dpi = 200,
     plot =  print(plot(b_p)) )


```
