---
title: "Visualize Results - Hilbert - Fall 2020"
author: "Brooke Staveland"
date: "4/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
ggthemr("solarized")

## parallelization ##
nCores <- 2
registerDoParallel(nCores)

```

# Dictator Game Regression Results

This analysis script visualizes the output of the permuted regressions.

## Load Presentation

Load and prep presentation-locked results for all subjects.

```{r concatenate-results-presentation, echo = F}

### any subject general vars ###
spec_vars <- c("*", "*")
abs_beta_val <- F
regions_to_combine <- c("All")
 
# IR39 has strange behavior # 
# ## IR39 ##
# 
# # combine different csvs #
# presentation_results_39 <- compile_results(regions = regions_to_combine,
#                                            type = "pres-locked",
#                                            sub = "IR39",
#                                            spec_vars = spec_vars,
#                                            path = path(here(), "results", "IR39", "insula"),
#                                            absBeta = F)
# 



## IR35 ##

# combine different csvs #
hfa_presentation_results_35 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-pres-locked-hilbertRS", 
                                           sub = "IR35", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR35", "post_eda"), 
                                           absBeta = abs_beta_val)

theta_presentation_results_35 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-pres-locked-hilbertRS", 
                                           sub = "IR35", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR35", "post_eda"), 
                                           absBeta = abs_beta_val)


# ## IR19 has weird behavior  ##
# 
# # combine different csvs #
# theta_presentation_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "theta-pres-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all"), 
#                                            absBeta = abs_beta_val)
# 
# hfa_presentation_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "hfa-pres-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all"), 
#                                            absBeta = abs_beta_val)
# 



## IR16 ##

# combine different csvs #
hfa_presentation_results_16 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR16",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR16", "post_eda"),
                                           absBeta = F)

theta_presentation_results_16 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR16",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR16", "post_eda"),
                                           absBeta = F)


## IR57 ##

# combine different csvs #
hfa_presentation_results_57 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR57",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR57", "post_eda"),
                                           absBeta = F)

theta_presentation_results_57 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR57",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR57", "post_eda"),
                                           absBeta = F)



## IR9 ##

# combine different csvs #
hfa_presentation_results_9 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR9",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR9", "post_eda"),
                                           absBeta = F)

theta_presentation_results_9 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR9",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR9", "post_eda"),
                                           absBeta = F)

## IR10 ##

# combine different csvs #
hfa_presentation_results_10 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR10",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR10", "post_eda"),
                                           absBeta = F)

theta_presentation_results_10 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR10",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR10", "post_eda"),
                                           absBeta = F)
## IR26 ##

# combine different csvs #
hfa_presentation_results_26 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR26",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR26", "post_eda"),
                                           absBeta = F)

theta_presentation_results_26 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR26",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR26", "post_eda"),
                                           absBeta = F)

## IR28 ##

# combine different csvs #
hfa_presentation_results_28 <- compile_results(regions = regions_to_combine,
                                           type = "hfa-pres-locked-hilbertRS",
                                           sub = "IR28",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR28", "post_eda"),
                                           absBeta = F)

theta_presentation_results_28 <- compile_results(regions = regions_to_combine,
                                           type = "theta-pres-locked-hilbertRS",
                                           sub = "IR28",
                                           spec_vars = spec_vars,
                                           path = path(here(), "results", "IR28", "post_eda"),
                                           absBeta = F)


```

## Load Choice

Load and prep choice-locked results for all subjects.

```{r concatenate-results-choice, echo =F}

### any subject general vars ###
spec_vars <- c("*", "*")
abs_beta_val <- F
regions_to_combine <- c("All")
  
# ## IR39 ##
# 
# # combine different csvs #
# choice_results_39_all <- compile_results(regions = regions_to_combine,
#                                            type = "choice-locked",
#                                            sub = "IR39",
#                                            spec_vars = spec_vars,
#                                            path = path(here(), "results", "IR39"),
#                                            absBeta = F)
# 


## IR35 ##

# # combine different csvs #
# delta_choice_results_35 <- compile_results(regions = regions_to_combine, 
#                                            type = "delta-choice-locked-hilbertRS", 
#                                            sub = "IR35", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR35", "all", "choice"), 
#                                            absBeta = abs_beta_val)

theta_choice_results_35 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR35", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR35", "post_eda"), 
                                           absBeta = abs_beta_val)
# alpha_choice_results_35 <- compile_results(regions = regions_to_combine, 
#                                            type = "alpha-choice-locked-hilbertRS", 
#                                            sub = "IR35", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR35", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# beta_choice_results_35 <- compile_results(regions = regions_to_combine, 
#                                            type = "beta-choice-locked-hilbertRS", 
#                                            sub = "IR35", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR35", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# gamma_choice_results_35 <- compile_results(regions = regions_to_combine, 
#                                            type = "gamma-choice-locked-hilbertRS", 
#                                            sub = "IR35", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR35", "all", "choice"), 
#                                            absBeta = abs_beta_val)

hfa_choice_results_35 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR35", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR35", "post_eda"), 
                                           absBeta = abs_beta_val)



# ## IR19 ##
# 
# # combine different csvs #
# delta_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "delta-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# theta_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "theta-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# alpha_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "alpha-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# beta_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "beta-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# gamma_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "gamma-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# hfa_choice_results_19 <- compile_results(regions = regions_to_combine, 
#                                            type = "hfa-choice-locked-hilbertRS", 
#                                            sub = "IR19", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR19", "all", "choice"), 
#                                            absBeta = abs_beta_val)

# # runa anova for inequity results #
# path_hg_clean <- path(here(), "munge", "IR19", "hg_behave_choice_locked_cut_fixation_150_insula.csv")
# hg_behave <-  read.csv(path_hg_clean)
# hg_behave <- hg_behave %>% mutate(electrodes = gsub("POL ", "", electrodes)) # IR19 has weird elec names
# run_filtered_anova(results = choice_results_19, 
#                    brain_behave_data = hg_behave, 
#                    sub = "IR19", 
#                    region_name = "All", 
#                    reg_name_one = reg_name_one, 
#                    reg_name_two = reg_name_two,                    
#                    all_results = T, 
#                    type = "choice-locked_insula")
# 
# # read back in the results #
# region_name <- "All"
# adv_choice_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_one, ".csv")))
# dis_choice_results_for_plots_19 <- read.csv(fs::path(here(), "results", "IR19", paste0(region_name, "_choice-locked_insula_anova_results_", reg_name_two, ".csv")))


## IR57 ##

# # combine different csvs #
# delta_choice_results_57 <- compile_results(regions = regions_to_combine, 
#                                            type = "delta-choice-locked-hilbertRS", 
#                                            sub = "IR57", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR57", "all", "choice"), 
#                                            absBeta = abs_beta_val)

theta_choice_results_57 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR57", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR57", "post_eda"), 
                                           absBeta = abs_beta_val)
# alpha_choice_results_57 <- compile_results(regions = regions_to_combine, 
#                                            type = "alpha-choice-locked-hilbertRS", 
#                                            sub = "IR57", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR57", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# beta_choice_results_57 <- compile_results(regions = regions_to_combine, 
#                                            type = "beta-choice-locked-hilbertRS", 
#                                            sub = "IR57", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR57", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# gamma_choice_results_57 <- compile_results(regions = regions_to_combine, 
#                                            type = "gamma-choice-locked-hilbertRS", 
#                                            sub = "IR57", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR57", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
hfa_choice_results_57 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR57", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR57", "post_eda"), 
                                           absBeta = abs_beta_val)


## IR28 ##

# # combine different csvs #
# delta_choice_results_28 <- compile_results(regions = regions_to_combine, 
#                                            type = "delta-choice-locked-hilbertRS", 
#                                            sub = "IR28", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR28", "all", "choice"), 
#                                            absBeta = abs_beta_val)

theta_choice_results_28 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR28", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR28", "post_eda"), 
                                           absBeta = abs_beta_val)
# alpha_choice_results_28 <- compile_results(regions = regions_to_combine, 
#                                            type = "alpha-choice-locked-hilbertRS", 
#                                            sub = "IR28", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR28", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# beta_choice_results_28 <- compile_results(regions = regions_to_combine, 
#                                            type = "beta-choice-locked-hilbertRS", 
#                                            sub = "IR28", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR28", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
# gamma_choice_results_28 <- compile_results(regions = regions_to_combine, 
#                                            type = "gamma-choice-locked-hilbertRS", 
#                                            sub = "IR28", 
#                                            spec_vars = spec_vars, 
#                                            path = path(here(), "results", "IR28", "all", "choice"), 
#                                            absBeta = abs_beta_val)
# 
hfa_choice_results_28 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR28", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR28", "post_eda"), 
                                           absBeta = abs_beta_val)


## IR9 ##

# combine different csvs #
theta_choice_results_9 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR9", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR9", "post_eda"), 
                                           absBeta = abs_beta_val)

hfa_choice_results_9 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR9", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR9", "post_eda"), 
                                           absBeta = abs_beta_val)

## IR10 ##

# combine different csvs #
theta_choice_results_10 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR10", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR10", "post_eda"), 
                                           absBeta = abs_beta_val)

hfa_choice_results_10 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR10", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR10", "post_eda"), 
                                           absBeta = abs_beta_val)

## IR26 ##

# combine different csvs #
theta_choice_results_26 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR26", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR26", "post_eda"), 
                                           absBeta = abs_beta_val)

hfa_choice_results_26 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR26", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR26", "post_eda"), 
                                           absBeta = abs_beta_val)

## IR16 ##

# combine different csvs #
theta_choice_results_16 <- compile_results(regions = regions_to_combine, 
                                           type = "theta-choice-locked-hilbertRS", 
                                           sub = "IR16", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR16", "post_eda"), 
                                           absBeta = abs_beta_val)

hfa_choice_results_16 <- compile_results(regions = regions_to_combine, 
                                           type = "hfa-choice-locked-hilbertRS", 
                                           sub = "IR16", 
                                           spec_vars = spec_vars, 
                                           path = path(here(), "results", "IR16", "post_eda"), 
                                           absBeta = abs_beta_val)


```


## plotting functions

```{r plotting-functions, echo = F}
ggthemr::ggthemr("pale", layout = "plain")
getPalette = colorRampPalette(brewer.pal(10, "Set1"))

ineq_plots <- function(df, title) {
# plots the bar plots of dif in R2 for inequity  
df %>%
    ungroup() %>%
    mutate(sig = if_else(perm_p < 0.05 & anova_p < 0.01, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes( x = bin, y = diff_adj_r2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Difference in Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)
  
}

ineq_plots_choice <- function(df, title) {
# plots the bar plots of dif in R2 for inequity  
df %>%
    ungroup() %>%
    mutate(sig = if_else(perm_p < 0.05 & anova_p < 0.01, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes( x = bin, y = diff_adj_r2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Difference in Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)
  
}

active_elec_plots <- function(df, var, title) {
  df %>%
    filter(predictor == var) %>%
    mutate(sig = if_else(perm_p < 0.0125 & p < 0.05, "Significant", "Insignificant")) %>%
    mutate_cond(sig == "Significant", sig = as.character(region)) %>%
    mutate(sig = relevel(factor(sig), ref = "Insignificant")) %>%
    # mutate(bin = factor(bin, levels = colnames(hg_data)[4:38])) %>%
    ggplot(., aes( x = bin, y = R2, color = sig, fill = sig)) +
    geom_col(alpha = .5) +
    # geom_vline(aes(xintercept = which(levels(bin) %in% "post_1"))) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.background = element_rect(fill = "white")) + 
    scale_fill_manual(values = c("grey", getPalette(4))) +
    scale_color_manual(values = c("grey", getPalette(4))) +
    labs(y = "Adj. R Squared", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode) + 
    ggtitle(title)

}

combined_active_plots <- function(df, subject, num_rows, sig_thresh, vars = c("self_payoff", "self_foregone", "other_payoff", "other_foregone")){
  df  %>%
    filter(predictor %in% vars) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    # mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor_sig = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor_sig = relevel(factor(predictor_sig, levels = c("Insig", vars)), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor_sig, color = predictor_sig)) + 
    geom_col(alpha = .5) + 
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~ROI, nrow = num_rows) +
    ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}

combined_active_plots_choice <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    # filter(!predictor %in% c("ineq_advent", "ineq_disadvent")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor = relevel(factor(predictor), ref = "Insig")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor, color = predictor)) + 
    geom_col(alpha = .5) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Region", color = "Region") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}

combined_active_plots_for_talk <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    filter(!predictor %in% c("ineq_advent", "ineq_disadvent", "self_diff", "other_diff")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(Beta = if_else(predictor == "ineq_advent", Beta * -1, Beta)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor_case = if_else(grepl("other|disadvent", predictor), "ther", "elf")) %>%
    mutate(predictor_case = if_else(bin_sig == 0, "Insig", as.character(predictor_case))) %>%
    mutate(predictor_case = relevel(factor(predictor_case), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor_case, color = predictor_case)) + 
    geom_col(alpha = .5) + 
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(9))) +
      scale_color_manual(values = c("grey", getPalette(9))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Regressor", color = "Regressor") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject))
}



combined_active_plots_choice_for_talk <- function(df, subject, num_rows, sig_thresh){
  df  %>%
    # filter(!predictor %in% c("ineq_advent", "ineq_disadvent")) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(bin_sig = if_else(Beta < 0 & bin_sig == 1, -1, bin_sig)) %>%
    group_by(bin, electrode) %>%
    mutate(bin_sum = sum(bin_sig)/6) %>%
    ungroup() %>%
    mutate(predictor_case = if_else(grepl("other|disadvent", predictor), "other", "self")) %>%
    mutate(predictor_case = if_else(bin_sig == 0, "Insig", as.character(predictor_case))) %>%
    mutate(predictor_case = relevel(factor(predictor_case), ref = "Insig")) %>%
    mutate(bin = gsub("pre_", "-", bin)) %>%
    mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
    arrange(bin) %>%
    ggplot(., aes(x= bin, y = bin_sig, fill = predictor_case, color = predictor_case)) + 
    geom_col(alpha = .5) + 
    geom_vline(xintercept = 0, color = "black") +
    theme(axis.text.x = element_text(angle = 90),
          # axis.ticks.x = element_blank(),
          panel.background = element_rect(fill = "white")) +
      scale_fill_manual(values = c("grey", getPalette(8))) +
      scale_color_manual(values = c("grey", getPalette(8))) +
      labs(y = "number of sig. predictors", x = "Bins", fill = "Regressor", color = "Regressor") +
    facet_wrap(~electrode, nrow = num_rows) +
    ggtitle(paste0(subject))
}

beta_plots_all_subjects <- function(df, subject, sig_thresh, nrows, vars = c("self_payoff", "ineq_advent", "other_payoff", "ineq_disadvent")){
   plot_df <- df %>%
    filter(predictor %in% vars) %>%
    mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
    mutate(predictor_sig = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
    mutate(predictor_sig = relevel(factor(predictor_sig, levels = c("Insig", vars)), ref = "Insig")) %>%
    mutate(bin = as.numeric(gsub("bin_", "", bin))) %>%
    arrange(bin)
   
   # create labeler for ROIs
    roi_labels <- paste(plot_df$ROI, "\n elec: ", plot_df$electrode)
    names(roi_labels) <- plot_df$electrode
    
    plot_df %>%
      ggplot(., aes(x = bin, y= Beta)) +
      geom_line(aes(group = predictor), color = "grey", alpha = .3) +
      geom_point(aes(color = predictor_sig), size = 3) + 
      geom_vline(xintercept = 0, color = "black") +
      theme(axis.text.x = element_text(angle = 90),
            # axis.ticks.x = element_blank(),
            panel.background = element_rect(fill = "white")) +
        scale_fill_manual(values = c("grey", getPalette(9)), drop = F) +
        scale_color_manual(values = c("grey", getPalette(9)), drop = F) +
        labs(y = "Beta", x = "Bins",  color = "Regressor") +
      facet_wrap(~electrode, nrow = nrows, labeller = as_labeller(roi_labels)) +
      ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}

beta_plots_all_subjects_choice <- function(df, subject, sig_thresh, nrows, vars = c("self_payoff", "ineq_advent", "other_payoff", "ineq_disadvent"), regions = c("*")){
      
    plot_df <- df %>%
        filter(predictor %in% vars) %>%
        filter(grepl(paste(regions, collapse = "|"), ROI)) %>%
        mutate(bin_sig = if_else((p < .05 & perm_p < sig_thresh), 1, 0)) %>%
        mutate(predictor_sig = if_else(bin_sig == 0, "Insig", as.character(predictor))) %>%
        mutate(predictor_sig = relevel(factor(predictor_sig, levels = c("Insig", vars)), ref = "Insig")) %>%
        mutate(bin = gsub("pre_", "-", bin)) %>%
        mutate(bin = as.numeric(gsub("post_", "", bin))) %>%
        arrange(bin)
    
    # create labeler for ROIs
    roi_labels <- paste(plot_df$ROI, "\n elec: ", plot_df$electrode)
    names(roi_labels) <- plot_df$electrode
      
    plot_df %>%  
        ggplot(., aes(x = bin, y= Beta, color = predictor_sig)) +
        geom_line(aes(group = predictor), color = "grey", alpha = .3) +
        geom_point(aes(color = predictor_sig), size = 3) + 
        geom_vline(xintercept = 0, color = "black") +
        geom_vline(xintercept = 20, color = "black") +
        theme(axis.text.x = element_text(angle = 90),
              # axis.ticks.x = element_blank(),
              panel.background = element_rect(fill = "white")) +
          scale_fill_manual(values = c("grey", getPalette(9)), drop = F) +
          scale_color_manual(values = c("grey", getPalette(9)), drop = F) +
          labs(y = "Beta", x = "Bins",  color = "Regressor") +
        facet_wrap(~electrode, nrow = nrows, labeller = as_labeller(roi_labels)) +
        ggtitle(paste0(subject, " ~ thresh @ ", sig_thresh))
}



```

## Presentation Results

```{r clean-presentation-results, echo = F}


merge_with_elec_info <- function(df, localizations_sub) {
## merge df with elec info, stored in localizations_sub
## creates new var of form ROI1-ROI2  
## also cleans elec names
  
  # clean the names
  df <- df %>%
    mutate(electrode = gsub("POL ", "", electrode)) %>%
    mutate(electrode = gsub(" POL", "", electrode)) %>%
    mutate(electrode = gsub("-Ref", "", electrode)) %>%
    mutate(electrode = gsub("-Ref-", "-", electrode)) 
  
  # separate two electrodes
  df <- df %>%
    mutate(first_elec= gsub("-.*", "", electrode)) %>%
    mutate(second_elec = gsub(".*-", "", electrode))
  # join on first electrode
  df <- left_join(df,
                 localizations_sub,
                 by = c("first_elec" = "Electrode"))
  # rename to `first_region`
  df <- df %>%
    rename(first_region = `Loc Meeting`)
  # join on second electrode and rename
  df <-  left_join(df,
             localizations_sub,
             by = c("second_elec" = "Electrode")) %>%
    rename(second_region = `Loc Meeting`) 
  # paste into useful format
  df <- df %>% mutate(ROI = paste0(first_region, "-", second_region))
  
  return(df)

}


## get region names ##
localizations <- read_csv(path(here(), "munge", "combined_electrode_info_cleaned.csv"))
localizations_28 <- localizations %>% filter(subject == "IR28") %>% select(Electrode, `Loc Meeting`)
localizations_35 <- localizations %>% filter(subject == "IR35") %>% select(Electrode, `Loc Meeting`)
localizations_57 <- localizations %>% filter(subject == "IR57") %>% select(Electrode, `Loc Meeting`)
localizations_9 <- localizations %>% filter(subject == "IR9") %>% select(Electrode, `Loc Meeting`)
localizations_10 <- localizations %>% filter(subject == "IR10") %>% select(Electrode, `Loc Meeting`)
localizations_10 <- localizations_10 %>%
  mutate(Electrode = gsub("POL ", "", Electrode)) %>%
  mutate(Electrode = gsub(" POL", "", Electrode)) %>%
  mutate(Electrode = gsub("-Ref", "", Electrode)) %>%
  mutate(Electrode = gsub("-Ref-", "-", Electrode)) 
localizations_26 <- localizations %>% filter(subject == "IR26") %>% select(Electrode, `Loc Meeting`)
localizations_16 <- localizations %>% filter(subject == "IR16") %>% select(Electrode, `Loc Meeting`)

### clean data ###
theta_presentation_cleaned_results_9 <- merge_with_elec_info(theta_presentation_results_9,
                                                              localizations_9)
hfa_presentation_cleaned_results_9 <- merge_with_elec_info(hfa_presentation_results_9,
                                                            localizations_9)
theta_presentation_cleaned_results_10 <- merge_with_elec_info(theta_presentation_results_10,
                                                              localizations_10)
hfa_presentation_cleaned_results_10 <- merge_with_elec_info(hfa_presentation_results_10,
                                                            localizations_10)
theta_presentation_cleaned_results_16 <- merge_with_elec_info(theta_presentation_results_16,
                                                              localizations_16)
hfa_presentation_cleaned_results_16 <- merge_with_elec_info(hfa_presentation_results_16,
                                                            localizations_16)
theta_presentation_cleaned_results_26 <- merge_with_elec_info(theta_presentation_results_26,
                                                              localizations_26)
hfa_presentation_cleaned_results_26 <- merge_with_elec_info(hfa_presentation_results_26,
                                                            localizations_26)

theta_presentation_cleaned_results_28 <- merge_with_elec_info(theta_presentation_results_28,
                                                              localizations_28)
hfa_presentation_cleaned_results_28 <- merge_with_elec_info(hfa_presentation_results_28,
                                                            localizations_28)

theta_presentation_cleaned_results_35 <- merge_with_elec_info(theta_presentation_results_35,
                                                              localizations_35)
hfa_presentation_cleaned_results_35 <- merge_with_elec_info(hfa_presentation_results_35,
                                                            localizations_35)

theta_presentation_cleaned_results_57 <- merge_with_elec_info(theta_presentation_results_57,
                                                              localizations_57)
hfa_presentation_cleaned_results_57 <- merge_with_elec_info(hfa_presentation_results_57,
                                                            localizations_57)

## split left and right for plotting ##
left_theta_presentation_cleaned_results_9 <- theta_presentation_cleaned_results_9 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_9 <- theta_presentation_cleaned_results_9 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_9 <- hfa_presentation_cleaned_results_28 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_9 <- hfa_presentation_cleaned_results_28 %>% filter(grepl("^R", electrode))

left_theta_presentation_cleaned_results_10 <- theta_presentation_cleaned_results_10 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_10 <- theta_presentation_cleaned_results_10 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_10 <- hfa_presentation_cleaned_results_10 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_10 <- hfa_presentation_cleaned_results_10 %>% filter(grepl("^R", electrode))

left_theta_presentation_cleaned_results_16 <- theta_presentation_cleaned_results_16 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_16 <- theta_presentation_cleaned_results_16 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_16 <- hfa_presentation_cleaned_results_16 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_16 <- hfa_presentation_cleaned_results_16 %>% filter(grepl("^R", electrode))

left_theta_presentation_cleaned_results_26 <- theta_presentation_cleaned_results_26 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_26 <- theta_presentation_cleaned_results_26 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_26 <- hfa_presentation_cleaned_results_26 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_26 <- hfa_presentation_cleaned_results_26 %>% filter(grepl("^R", electrode))



left_theta_presentation_cleaned_results_28 <- theta_presentation_cleaned_results_28 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_28 <- theta_presentation_cleaned_results_28 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_28 <- hfa_presentation_cleaned_results_28 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_28 <- hfa_presentation_cleaned_results_28 %>% filter(grepl("^R", electrode))

left_theta_presentation_cleaned_results_35 <- theta_presentation_cleaned_results_35 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_35 <- theta_presentation_cleaned_results_35 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_35 <- hfa_presentation_cleaned_results_35 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_35 <- hfa_presentation_cleaned_results_35 %>% filter(grepl("^R", electrode))


left_theta_presentation_cleaned_results_57 <- theta_presentation_cleaned_results_57 %>% filter(grepl("^L", electrode))
right_theta_presentation_cleaned_results_57 <- theta_presentation_cleaned_results_57 %>% filter(grepl("^R", electrode))

left_hfa_presentation_cleaned_results_57 <- hfa_presentation_cleaned_results_57 %>% filter(grepl("^L", electrode))
right_hfa_presentation_cleaned_results_57 <- hfa_presentation_cleaned_results_57 %>% filter(grepl("^R", electrode))


```

```{r pres_viz, echo = F, fig.width= 18, fig.height= 22}

## Theta ##
beta_plots_all_subjects(left_theta_presentation_cleaned_results_57, "IR57 ~ Left ~ Theta ~ Pres", 10, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_57, "IR57 ~ Right ~ Theta ~ Pres", 10, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_35, "IR35 ~ Left ~ Theta ~ Pres", 10, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_35, "IR35 ~ Right ~ Theta ~ Pres", 10, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_28, "IR28 ~ Left ~ Theta ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_28, "IR28 ~ Right ~ Theta ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_9, "IR9 ~ Left ~ Theta ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_9, "IR9 ~ Right ~ Theta ~ Pres", 9, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_10, "IR10 ~ Left ~ Theta ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_10, "IR10 ~ Right ~ Theta ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_26, "IR26 ~ Left ~ Theta ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_26, "IR26 ~ Right ~ Theta ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_theta_presentation_cleaned_results_16, "IR16 ~ Left ~ Theta ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_theta_presentation_cleaned_results_16, "IR16 ~ Right ~ Theta ~ Pres", 8, sig_thresh = 0.01)

## HFA ##
beta_plots_all_subjects(left_hfa_presentation_cleaned_results_57, "IR57 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_57, "IR57 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_35, "IR35 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_35, "IR35 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_28, "IR28 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_28, "IR28 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_9, "IR9 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_9, "IR9 ~ Right ~ HFA ~ Pres", 9, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_10, "IR10 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_10, "IR10 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_26, "IR26 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_26, "IR26 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

beta_plots_all_subjects(left_hfa_presentation_cleaned_results_16, "IR16 ~ Left ~ HFA ~ Pres", 8, sig_thresh = 0.01)
beta_plots_all_subjects(right_hfa_presentation_cleaned_results_16, "IR16 ~ Right ~ HFA ~ Pres", 8, sig_thresh = 0.01)

```





```{r choice-prep, echo = F}

# IR35 #
theta_choice_cleaned_results_35 <- merge_with_elec_info(theta_choice_results_35, localizations_35)
hfa_choice_cleaned_results_35 <- merge_with_elec_info(hfa_choice_results_35, localizations_35)
# IR57#
theta_choice_cleaned_results_57 <- merge_with_elec_info(theta_choice_results_57, localizations_57)
hfa_choice_cleaned_results_57 <- merge_with_elec_info(hfa_choice_results_57, localizations_57)
# IR28 #
theta_choice_cleaned_results_28 <- merge_with_elec_info(theta_choice_results_28, localizations_28)
hfa_choice_cleaned_results_28 <- merge_with_elec_info(hfa_choice_results_28, localizations_28)
# IR9 #
theta_choice_cleaned_results_9 <- merge_with_elec_info(theta_choice_results_9, localizations_9)
hfa_choice_cleaned_results_9 <- merge_with_elec_info(hfa_choice_results_9, localizations_9)
# IR10 #
theta_choice_cleaned_results_10 <- merge_with_elec_info(theta_choice_results_10, localizations_10)
hfa_choice_cleaned_results_10 <- merge_with_elec_info(hfa_choice_results_10, localizations_10)
# IR26 #
theta_choice_cleaned_results_26 <- merge_with_elec_info(theta_choice_results_26, localizations_26)
hfa_choice_cleaned_results_26 <- merge_with_elec_info(hfa_choice_results_26, localizations_26)
# IR16 #
theta_choice_cleaned_results_16 <- merge_with_elec_info(theta_choice_results_16, localizations_26)
hfa_choice_cleaned_results_16 <- merge_with_elec_info(hfa_choice_results_26, localizations_26)

# theta #
left_theta_choice_cleaned_results_35 <- theta_choice_cleaned_results_35 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_35 <- theta_choice_cleaned_results_35 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_57 <- theta_choice_cleaned_results_57 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_57 <- theta_choice_cleaned_results_57 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_28 <- theta_choice_cleaned_results_28 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_28 <- theta_choice_cleaned_results_28 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_9 <- theta_choice_cleaned_results_9 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_9 <- theta_choice_cleaned_results_9 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_10 <- theta_choice_cleaned_results_10 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_10 <- theta_choice_cleaned_results_10 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_26 <- theta_choice_cleaned_results_26 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_26 <- theta_choice_cleaned_results_26 %>% filter(grepl("^R", electrode))
left_theta_choice_cleaned_results_16 <- theta_choice_cleaned_results_16 %>% filter(grepl("^L", electrode))
right_theta_choice_cleaned_results_16 <- theta_choice_cleaned_results_16 %>% filter(grepl("^R", electrode))


# hfa #
left_hfa_choice_cleaned_results_35 <- hfa_choice_cleaned_results_35 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_35 <- hfa_choice_cleaned_results_35 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_57 <- hfa_choice_cleaned_results_57 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_57 <- hfa_choice_cleaned_results_57 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_28 <- hfa_choice_cleaned_results_28 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_28 <- hfa_choice_cleaned_results_28 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_9 <- hfa_choice_cleaned_results_9 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_9 <- hfa_choice_cleaned_results_9 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_10 <- hfa_choice_cleaned_results_10 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_10 <- hfa_choice_cleaned_results_10 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_26 <- hfa_choice_cleaned_results_26 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_26 <- hfa_choice_cleaned_results_26 %>% filter(grepl("^R", electrode))
left_hfa_choice_cleaned_results_16 <- hfa_choice_cleaned_results_16 %>% filter(grepl("^L", electrode))
right_hfa_choice_cleaned_results_16 <- hfa_choice_cleaned_results_16 %>% filter(grepl("^R", electrode))



```

```{r choice-viz, echo = F, fig.width= 18, fig.height= 22}

## theta ##

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_35, "IR35 ~ Left ~ Theta ~ Choice", 10, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_35, "IR35 ~ Right ~ Theta ~ Choice", 10, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_57, "IR57 ~ Left ~ Theta ~ Choice", 10, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_57, "IR57 ~ Right ~ Theta ~ Choice", 10, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_28, "IR28 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_28, "IR28 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_9, "IR9 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_9, "IR9 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_10, "IR10 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_10, "IR10 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_26, "IR26 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_26, "IR26 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_16, "IR16 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_16, "IR16 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

## HFA ##

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_35, "IR35 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_35, "IR35 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_57, "IR57 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_57, "IR57 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_28, "IR28 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_28, "IR28 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_9, "IR9 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_9, "IR9 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_10, "IR10 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_10, "IR10 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_hfa_choice_cleaned_results_26, "IR26 ~ Left ~ hfa ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_hfa_choice_cleaned_results_26, "IR26 ~ Right ~ hfa ~ Choice", 8, sig_thresh = 0.01)

beta_plots_all_subjects_choice(left_theta_choice_cleaned_results_16, "IR16 ~ Left ~ Theta ~ Choice", 8, sig_thresh = 0.01)
beta_plots_all_subjects_choice(right_theta_choice_cleaned_results_16, "IR16 ~ Right ~ Theta ~ Choice", 8, sig_thresh = 0.01)

```



