---
title: 'August EDA 2020: Subsampled Trials'
output: html_document
author: "Brooke Staveland"
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,  warning=FALSE, message=FALSE, fig.width=12,  fig.height=8, fig.align="center",  fig.pos="H",  cache=TRUE) 

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(janitor)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions.R"))
source(path(here(), "R", "compile_results.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", "merge_stepped_anova_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))

## plotting helpers ##
ggthemr("solarized")

## parallelization ##
nCores <- 2
registerDoParallel(nCores)

```


```{r behave-prep, echo = F}

# path to beahvioral files #
path_to_raw_behave <- fs::path(here(), "../dg_behave_formatted")
path_to_behave_munge <- fs::path(here(), "munge", "combined_behavioral_data.csv")
path_to_behave_clean <- fs::path(here(), "munge", "clean_behavioral_data.csv")

# concactenate behavioral data #
load_behave_data(path_to_raw_behave)

# prep behavioral data #
prep_behave_data(path_to_behave_munge)

# load clean data #
behave_data <- read.csv(path_to_behave_clean)

# table(behave_data$ineq_advent_choice)
# table(behave_data_08$ineq_disadvent_choice)
# table(behave_data_11$ineq_disadvent_choice)
# table(behave_data_12$ineq_disadvent_choice)
```


```{r trial-types, echo = F}

# behave_data %>%
#   filter(self_var_payoff == other_var_payoff) %>%
#   mutate(greater_than_ten = if_else(self_var_payoff < 10, "less", "more")) %>%
#   select(SID, chose_equality, greater_than_ten) %>%
#   group_by(SID) %>%
#   tabyl(SID, chose_equality, greater_than_ten) %>%
#   kable(.) %>%
#   kable_styling()

# There are three types of trials, trials without equality, trials where the advantage is in the dictator's favor and the reverse

behave_data <- behave_data %>%
  mutate(trial_type = if_else(self_var_payoff == other_var_payoff, "equality", if_else(self_var_payoff > other_var_payoff, "Advantageous", "Disadvantageous")))

# filter to current subject #
behave_data_08 <- behave_data %>% filter(SID == "DG_s08")
behave_data_11 <- behave_data %>% filter(SID == "DG_s11")
behave_data_12 <- behave_data %>% filter(SID == "DG_s12")
behave_data_06 <- behave_data %>% filter(SID == "DG_s06")
behave_data_13 <- behave_data %>% filter(SID == "DG_s13")
```


```{r active-electrodes, echo = F, warning=F}

test_for_sig_above_baseline <- function(col, elec_baseline) {
    # t test against baseline
    result <- t.test(elec_baseline$baseline_mean, col)
    return(result$p.value)
  }

# function to get electrodes with at least 20% bins have different hfa from baseline
get_active_electrodes <- function(file_path_to_power_data, 
                                  file_path_to_electrode_names,
                                  file_path_to_elecs_of_interest,
                                  choice = FALSE) {

  # load data #
  hg_data <- load_high_gamma_data(file_path_to_power_data, 
                                  file_path_to_electrode_names)

  # read in elecs #
  elecs_to_use <- read.csv(file_path_to_elecs_of_interest)
  
  # filter to good electrodes #
  hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))
  
  if(choice == FALSE) {
    # save baseline #
    baseline_data <- hg_data[, 1:200]
    hg_data <- hg_data[, 201:ncol(hg_data)]
    baseline_mean <- baseline_data %>% select(starts_with("time")) %>% apply(., 1, function(x) mean(x))
    baseline_mean <- data.frame(baseline_mean)
    baseline_mean <- cbind(baseline_mean, "electrodes" = hg_data$electrodes, "trial" = hg_data$trial)
    # write baseline csv for choice
    subject <- gsub("_.*", "", gsub(".*/", "", file_path_to_power_data))
    write_csv(baseline_mean, path(here(), "munge", "EDA", paste0(subject, "eda_baseline_mean.csv")))
  } else {
    
    subject <- gsub("_.*", "", gsub(".*/", "", file_path_to_power_data))
    baseline_mean <- read_csv(path(here(), "munge", "EDA", paste0(subject, "eda_baseline_mean.csv")))
  }
  
  matrix_ncols <-  hg_data %>% select(starts_with("time")) %>% ncol(.) + 1
  active_electrodes <- matrix(nrow = length( unique(hg_data$electrodes)), ncol = matrix_ncols)
  rownames(active_electrodes) <- unique(hg_data$electrodes)
  for(elec in unique(hg_data$electrodes)) {
    
    # filter to elecs of interest #
    elec_hg <- hg_data %>% filter(electrodes == elec) %>% select(starts_with("time"))
    elec_baseline <- baseline_mean %>% filter(electrodes == elec)
    
    # run t test between baseline and each time bin during the trial #
    p_vals <- apply(elec_hg, 2, function(x) test_for_sig_above_baseline(x, elec_baseline))
    
    # grab percentage if sig bins #
    sig_bins <- p_vals < .05
    longest_indices <- stretch_start_end(sig_bins)
    
    
    # if greater than 10% of bins are sig, mark as active
    if(is.na(longest_indices)[1] == TRUE) {
      active_electrodes[elec, 1] <- "inactive"
      active_electrodes[elec, 2:matrix_ncols] <- sig_bins
    } else if(longest_indices[2] - longest_indices[1] >= 50) {
      active_electrodes[elec, 1] <- "active"
      active_electrodes[elec, 2:matrix_ncols] <- sig_bins
    } else {
      active_electrodes[elec, 1] <- "inactive"
      active_electrodes[elec, 2:matrix_ncols] <- sig_bins
    }
    
    
    
  }
  
  active_electrodes_df <- as_data_frame(active_electrodes)
  colnames(active_electrodes_df) <- c("active", 
                                        colnames(hg_data %>% select(starts_with("time"))))
  active_electrodes_df$electrodes <- rownames(active_electrodes)

  return(active_electrodes_df)
}

clean_electrode_names <- function(df){
    # clean the names
  df <- df %>%
    mutate(electrodes = gsub("POL ", "", electrodes)) %>%
    mutate(electrodes = gsub(" POL", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref-", "-", electrodes)) 
  
  # separate two electrodes
  df <- df %>%
    mutate(first_elec= gsub("-.*", "", electrodes)) %>%
    mutate(second_elec = gsub(".*-", "", electrodes))
  
  return(df)
}

merge_with_elec_info_active <- function(df, localizations_sub) {
## merge df with elec info, stored in localizations_sub
## creates new var of form ROI1-ROI2  
## also cleans elec names
  
  # clean the names
  df <- df %>%
    mutate(electrodes = gsub("POL ", "", electrodes)) %>%
    mutate(electrodes = gsub(" POL", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref-", "-", electrodes)) 
  
  # separate two electrodess
  df <- df %>%
    mutate(first_elec= gsub("-.*", "", electrodes)) %>%
    mutate(second_elec = gsub(".*-", "", electrodes))
  # join on first electrode
  df <- left_join(df,
                 localizations_sub,
                 by = c("first_elec" = "Electrode"))
  # rename to `first_region`
  df <- df %>%
    rename(first_region = `Loc Meeting`)
  # join on second electrode and rename
  df <-  left_join(df,
             localizations_sub,
             by = c("second_elec" = "Electrode")) %>%
    rename(second_region = `Loc Meeting`) 
  # paste into useful format
  df <- df %>% mutate(ROI = paste0(first_region, "-", second_region))
  
  return(df)

}

## get localization data ##
localizations <- read_csv(path(here(), "munge", "combined_electrode_info_cleaned.csv"))
localizations_19 <- localizations %>% filter(subject == "IR19") %>% select(Electrode, `Loc Meeting`)
localizations_35 <- localizations %>% filter(subject == "IR35") %>% select(Electrode, `Loc Meeting`)
localizations_57 <- localizations %>% filter(subject == "IR57") %>% select(Electrode, `Loc Meeting`)



```

```{r hfa-trial-type-subsample, echo = F}


plots_power_envelope_trial_type_subsample <- function(hg_data,
                                              behave_data, 
                                              active_only_data, 
                                              elec,
                                              choice = FALSE) {

  behave_hg_data <- merge.data.frame(hg_data, behave_data, by.x = "trial", by.y = "round")
  
  
  
  # prep for plotting #
  elec_behave_hg <- behave_hg_data %>% 
    filter(electrodes == elec) %>%
    filter(!is.na(trial_type))
  
  trial_counts <- table(elec_behave_hg$trial_type)
  
 elec_behave_hg <- elec_behave_hg %>%
    mutate(sample_set = as.integer(1)) %>%
    mutate_cond(trial_type == "Advantageous", sample_set = sample(1:trial_counts[1], trial_counts[1]) ) %>%
    mutate_cond(trial_type == "Disadvantageous",sample_set = sample(1:trial_counts[2], trial_counts[2]) ) %>%
    filter(sample_set < 25) %>%
    gather(key = "time", value = "hfa", starts_with("time")) %>%
    group_by(time, trial_type) %>%
    mutate(lower_sem = mean(hfa) - 2*(sd(hfa)/n())) %>%
    mutate(upper_sem = mean(hfa) + 2*(sd(hfa)/n())) %>%
    mutate(mean = mean(hfa)) %>%
    mutate(time = as.numeric(gsub("time_", "", time)))
  
  elec_name <- active_only_data %>% filter(electrodes == elec)
  
  
    p <- elec_behave_hg %>%
      ggplot(., aes(x = time, y  = mean, color = trial_type, fill = trial_type)) +
      geom_line() +
      geom_ribbon(aes(ymin = lower_sem, ymax = upper_sem), alpha = .7) +
      geom_vline(xintercept = 200, color = "black") +
      theme(panel.background = element_rect(fill = "white")) +
      ggtitle(elec_name$ROI) +
      labs(subtitle = elec)
  
    plot(p)
  
}

```



```{r IR35-get-active-elecs-presentation, echo=FALSE, fig.width=12, fig.height=8}

### IR35 ###
# necessary paths #
file_path_to_power_data <- path(here(), "munge", "savio_cluster", "IR35_hfa_munge_presentation_locked_rscaler_2575.csv")
file_path_to_electrode_names <- path(here(), "munge", "savio_cluster", "IR35_electrodes_presentation_locked_rscaler_2575.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR35_elecs_of_interest.csv")

# grab electrodes
active_electrodes_IR35 <- get_active_electrodes(file_path_to_power_data, 
                                  file_path_to_electrode_names,
                                  file_path_to_elecs_of_interest)


## get region names ##
active_data_35 <- merge_with_elec_info_active(active_electrodes_IR35, localizations_35)
active_only_data_35 <- active_data_35 %>% filter(active == "active")


# Load data for plots

# load data #
hg_data <- load_high_gamma_data(file_path_to_power_data, 
                                file_path_to_electrode_names)

# read in elecs #
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))


# Subsampled version

for(elec in unique(active_only_data_35$electrodes)) {
  

  plots_power_envelope_trial_type_subsample(hg_data, 
                                     behave_data_11, 
                                     active_only_data_35, 
                                     elec,
                                     choice = F)
  
}

```




```{r IR57-get-active-elecs, eval=T, echo=F}

### IR57 ###
# necessary paths #
file_path_to_power_data <- path(here(), "munge", "savio_cluster", "IR57_hfa_munge_presentation_locked_rscaler_2575.csv")
file_path_to_electrode_names <- path(here(), "munge", "savio_cluster", "IR57_electrodes_presentation_locked_rscaler_2575.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR57_elecs_of_interest.csv")

# grab electrodes
active_electrodes_IR57 <- get_active_electrodes(file_path_to_power_data, 
                                  file_path_to_electrode_names,
                                  file_path_to_elecs_of_interest)


## get region names ##
active_data_57 <- merge_with_elec_info_active(active_electrodes_IR57, localizations_57)
active_only_data_57 <- active_data_57 %>% filter(active == "active")


# Load data for plots

# load data #
hg_data <- load_high_gamma_data(file_path_to_power_data, 
                                file_path_to_electrode_names)

# read in elecs #
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))
  

for(elec in unique(active_only_data_57$electrodes)) {
  plots_power_envelope_trial_type_subsample(hg_data, 
                                     behave_data_13, 
                                     active_only_data_57, 
                                     elec,
                                     choice = F)
  
}

```

```{r IR19-get-active-elecs, eval = T, echo=F}

### IR19 ###
# necessary paths #
file_path_to_power_data <- path(here(), "munge", "savio_cluster", "IR19_hfa_munge_presentation_locked_rscaler_2575.csv")
file_path_to_electrode_names <- path(here(), "munge", "savio_cluster", "IR19_electrodes_presentation_locked_rscaler_2575.csv")
file_path_to_elecs_of_interest <- path(here(), "munge", "IR19_elecs_of_interest.csv")

# grab electrodes
active_electrodes_IR19 <- get_active_electrodes(file_path_to_power_data, 
                                  file_path_to_electrode_names,
                                  file_path_to_elecs_of_interest)


## get region names ##
active_data_19 <- merge_with_elec_info_active(active_electrodes_IR19, localizations_19)
active_only_data_19 <- active_data_19 %>% filter(active == "active")


# Load data for plots

# load data #
hg_data <- load_high_gamma_data(file_path_to_power_data, 
                                file_path_to_electrode_names)

# read in elecs #
elecs_to_use <- read.csv(file_path_to_elecs_of_interest)

# filter to good electrodes #
hg_data <- hg_data %>% filter(grepl(paste(elecs_to_use$Electrode, collapse = "|"), electrodes))
  
# clean hg_data names
hg_data <- clean_electrode_names(hg_data)

for(elec in unique(active_only_data_19$electrodes)) {
  plots_power_envelope_trial_type_subsample(hg_data, 
                                     behave_data_08, 
                                     active_only_data_19, 
                                     elec,
                                     choice = F)
  
}

```


