---
title: "VIF fo All vs Ego Analyses"
output: html_document
---

```{r setup, include=FALSE}
#### batch script for regressions on scf cluster ###

### ALL SUBJECTS!!!! ###

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(zoo)
library(lme4)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "run_permuted_regressions_par.R"))
source(path(here(), "R", "run_filtered_anova.R"))
source(path(here(), "R", 'mutate_cond.R'))

```


```{r main_analysis}

## subs to run ##
subs <- c("IR9", "IR10", "IR16", "IR26", "IR28", "IR35", "IR57") # already ran IR35

vif_results <- NULL
for(sub in subs){
  
  # Null main file out each time #
  power_behave <- NULL
  
  print(sub)

  ## electrodes ##
  # load #
  file_path_to_elecs_of_interest <- path(here(), "munge", paste0(sub, "_elecs_of_interest.csv"))
  elecs_to_use <- read.csv(file_path_to_elecs_of_interest)
  # prep #
  all_elecs <- elecs_to_use %>% select(Electrode)
  
  ### theta ###
  
  ## read in data ##
  path_hp_clean <- path(here(), "munge", sub, "theta_behave_presentation_rscaler_2575_200.csv")
  power_behave <-  read.csv(path_hp_clean)
  # merge with elecs #
  brain_behave_data <- power_behave %>%
    filter(grepl(paste(all_elecs$Electrode, collapse = "|"), electrodes))
  all_electrodes <- unique(brain_behave_data$electrodes)
  # bin names #
  nBins <- colnames(power_behave %>% select(starts_with("bin_")))
  
  ## run regressions ##
  ## allocentric vs egocentric ##
  # pres #
  pres_vif_results <- data.frame(t(VIF(lm(bin_1 ~ ineq_disadvent + other_var_payoff, data = brain_behave_data)))) 
  # choice #
  choice_vif_results <- data.frame(t(VIF(lm(bin_1 ~ ineq_foregone + other_foregone, data = brain_behave_data))))
  
  sub_vif_results <- cbind(pres_vif_results, choice_vif_results)
  sub_vif_results$sub = sub
  
  
  if(is.null(vif_results)) {
    vif_results <- sub_vif_results
  } else {
    vif_results <- rbind(vif_results, sub_vif_results)
  }
  
  
  
}    
    
```
    
    
    
  